### PR TITLE
fix(effects): fix bugs in migration script to v18

### LINKED ISSUE #4397: 17.2.0 -> 18.0.0 Schematics wreak havoc in files
### Which @ngrx/* package(s) are the source of the bug?

schematics

### Minimal reproduction of the bug/regression with instructions

We are trying to upgrade a larger application. 
The application is running Angular 18, NGRX 17.2
After performing a seemingly successful upgrade with `ng update @ngrx/store ` , all imports in all files have errors and double entries.

**Example:**

A file using NGRX contains these imports (notice there is an import using path alias in the middle)

```
import {
    patchState,
    signalStore,
    withComputed,
    withHooks,
    withMethods,
    withState,
    getState
} from '@ngrx/signals';

import { ApiService } from '@shared/services/api';  // <-- import application using path alias
import { inject } from '@angular/core';
import { rxMethod } from '@ngrx/signals/rxjs-interop';
import { tapResponse } from '@ngrx/component-store';
import { pipe, switchMap, tap } from 'rxjs';
```

Now we run the migration:

```
We analyzed your package.json, there are some packages to update:

Name                                Version                  Command to update
 ---------------------------------------------------------------------------------
@ngrx/store                         17.2.0 -> 18.0.0         ng update @ngrx/store


 ng update @ngrx/store --force


Fetching dependency metadata from registry...
                  Package "ngrx-store-localstorage" has an incompatible peer dependency to "@ngrx/store" (requires "^17.0.0", would install "18.0.0").
    Updating package.json with dependency @ngrx/component-store @ "18.0.0" (was "17.2.0")...
    Updating package.json with dependency @ngrx/effects @ "18.0.0" (was "17.2.0")...
    Updating package.json with dependency @ngrx/router-store @ "18.0.0" (was "17.2.0")...
    Updating package.json with dependency @ngrx/store @ "18.0.0" (was "17.2.0")...
    Updating package.json with dependency @ngrx/store-devtools @ "18.0.0" (was "17.2.0")...
UPDATE package.json (4100 bytes)
✔ Packages successfully installed.
** Executing migrations of package '@ngrx/component-store' **

❯ As of NgRx v18, the `tapResponse` import has been removed from `@ngrx/component-store` in favor of the `@ngrx/operators` package.
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
    [@ngrx/component-store] Updated tapResponse to import from '@ngrx/operators'
UPDATE package.json (4134 bytes)
UPDATE src/app/features/accounting-transfers/accounting-transfers.store.ts (2993 bytes)
UPDATE src/app/features/accounting-transfers/components/edit-accounting-transfer/edit-accounting-transfer.store.ts (2487 bytes)
UPDATE src/app/features/administration/payment-transfers/payment-transfers.store.ts (2810 bytes)
UPDATE src/app/features/analyticsold/card-types/card-types.store.ts (3670 bytes)
UPDATE src/app/features/analyticsold/fresto-revenue/revenue.store.ts (4230 bytes)
UPDATE src/app/features/analyticsold/frontpage/analytics.store.ts (4334 bytes)
UPDATE src/app/features/analyticsold/payment-types/payment-types.store.ts (4754 bytes)
UPDATE src/app/features/analyticsold/slug-revenue/slug-revenue.store.ts (4617 bytes)
UPDATE src/app/features/companies/companies.store.ts (1515 bytes)
UPDATE src/app/features/company/company/company.store.ts (3526 bytes)
UPDATE src/app/features/company/company/components/company-stats/widget-revenue/revenue.store.ts (2069 bytes)
UPDATE src/app/features/company/company/dialogs/accounting-config/accounting-config.store.ts (3033 bytes)
UPDATE src/app/features/company/company/dialogs/cashdrawer/cashdrawer.store.ts (5828 bytes)
UPDATE src/app/features/company/company/dialogs/company-cache/company-cache.store.ts (2992 bytes)
UPDATE src/app/features/company/company/dialogs/company-terminal-credentials/company-terminal-credentials.store.ts (4623 bytes)
UPDATE src/app/features/company/company/dialogs/delete-company/delete-company.store.ts (2809 bytes)
UPDATE src/app/features/company/company/dialogs/edit-business-address/edit-business-address.store.ts (3548 bytes)
UPDATE src/app/features/company/company/dialogs/edit-business-data/edit-business-data.store.ts (3540 bytes)
UPDATE src/app/features/company/company/dialogs/edit-company-features/edit-company-features.store.ts (3635 bytes)
UPDATE src/app/features/company/company/dialogs/edit-company-status/edit-company-status.store.ts (3587 bytes)
UPDATE src/app/features/company/company/dialogs/edit-payment-config/edit-payment-config.store.ts (3878 bytes)
UPDATE src/app/features/company/company/dialogs/edit-vat/vat.store.ts (3935 bytes)
UPDATE src/app/features/company/company/dialogs/export-locations/export-locations.store.ts (4517 bytes)
UPDATE src/app/features/company/company/dialogs/import-bookings/import-bookings.store.ts (8021 bytes)
UPDATE src/app/features/create-company/create-company.store.ts (3046 bytes)
UPDATE src/app/features/logs/logs.store.ts (3382 bytes)
UPDATE src/app/features/parent-company/parent-company.store.ts (8150 bytes)
UPDATE src/app/features/parent-company/components/chains/chains.store.ts (3471 bytes)
UPDATE src/app/features/parent-company/components/chains/dialogs/chain/chain.store.ts (8522 bytes)
UPDATE src/app/features/parent-company/components/chains/dialogs/chain-members/chain-members.store.ts (10803 bytes)
UPDATE src/app/features/parent-company/components/edit-parent-company/edit-parent-company.store.ts (2652 bytes)
UPDATE src/app/features/parent-company/components/managers/managers.store.ts (2998 bytes)
UPDATE src/app/features/parent-company/components/managers/dialogs/create-edit-manager/create-edit-manager.store.ts (7684 bytes)
UPDATE src/app/features/reporting/z-reports.store.ts (2707 bytes)
UPDATE src/app/features/reporting/dialogs/report-details/report-details.store.ts (2521 bytes)
UPDATE src/app/features/terminals/create-edit-terminal/create-edit-terminal.store.ts (4812 bytes)
UPDATE src/app/features/terminals/delete-terminal/delete-terminal.store.ts (3404 bytes)
UPDATE src/app/features/terminals/move-terminal/move-terminal.store.ts (3868 bytes)
UPDATE src/app/shared/stores/config/config.store.ts (4482 bytes)
  Migration completed (40 files modified).

** Executing migrations of package '@ngrx/effects' **

❯ As of NgRx v18, the `concatLatestFrom` import has been removed from `@ngrx/effects` in favor of the `@ngrx/operators` package.
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
    [@ngrx/effects] Updated concatLatestFrom to import from '@ngrx/operators'
UPDATE package.json (4134 bytes)
UPDATE src/app/features/administration/administration.routes.ts (3058 bytes)
UPDATE src/app/features/company/company.routes.ts (1283 bytes)
UPDATE src/app/features/parent-companies/parent-companies.routes.ts (749 bytes)
UPDATE src/app/features/printers/printers.routes.ts (788 bytes)
UPDATE src/app/features/terminals/terminals.routes.ts (894 bytes)
UPDATE src/app/shared/store/index.ts (1720 bytes)
UPDATE src/app/shared/store/notifications/notifications.effects.ts (874 bytes)
UPDATE src/app/shared/store/parent-company/parent-company.effects.ts (3686 bytes)
UPDATE src/app/shared/store/printers/printers.effects.ts (7525 bytes)
UPDATE src/app/shared/store/router/router.effects.ts (851 bytes)
UPDATE src/app/shared/store/session/session.effects.ts (10125 bytes)
UPDATE src/app/shared/store/settings/settings.effects.ts (7209 bytes)
UPDATE src/app/shared/store/terminals/terminals.effects.ts (7913 bytes)
  Migration completed (14 files modified).

** Executing migrations of package '@ngrx/store' **

❯ As of NgRx v18, the `TypedAction` has been removed in favor of `Action`.
  Migration completed (No changes made).
```

After migration, the file now contains the following.

  ```
import {
    patchState,
    signalStore,
    withCoimport { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { ComponentStore } from '@ngrx/component-store';import { tapResponse } from '@ngrx/operators';
import { tapResponse } from '@ngrx/operators';
import { tapResponse } from '@ngrx/operators';
import { tapResponse } from '@ngrx/operators';
'@shared/services/api';
import { inject } from '@aimport { ComponentStore } from '@ngrx/component-store';import { tapResponse } from '@ngrx/operators';
import { tapResponse } from '@ngrx/operators';
import { tapResponse } from '@ngrx/operators';
xjs';

```

This happens to hundreds of files that contain NGRX imports.

### Expected behavior

Migration should not mess up imports /s

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

Ngrx: 17.2.0
Angular: 18.0.3
OS: MacOS Sonoma 14.2

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [X] No

### PR DESCRIPTION
**Pull request by rainerhahnekamp**
ChangeLog:
- Update 17.6: Remove `os.EOL`.

This commit fixes one major bug and some edge cases in the migration script.

- Reset the changes array with every file.
- Fix an issue when a file has multiple import declarations to `@ngrx/effects`.
- Print out a warning if `concatLatestFrom` is imported multiple times.

The same problem exists for the component store's migration script. I will provide a PR for that as well.

I'm afraid a new patch release is necessary. Apologies, I'm very sorry!

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[] Other... Please describe:
```

Closes #4397

## Does this PR introduce a breaking change?

```
[] Yes
[x] No
```

### CODE REVIEW

File: modules/effects/migrations/18_0_0-beta/index.ts [hunk 1]
```diff
@@ -107,7 +126,7 @@ export function migrateConcatLatestFromImport(): Rule {
           new InsertChange(
             sourceFile.fileName,
             effectsImportDeclaration.getEnd() + 1,
-            `${newOperatorsImport}\n`
+            `${newOperatorsImport}${os.EOL}`
```
Comment (timdeschryver) [inline modules/effects/migrations/18_0_0-beta/index.ts:129]: Thanks for the fix @rainerhahnekamp !
Could you please revert this change?
The reasoning is that we mainly use `\n` in other schematics, maybe this is incorrect but it makes snapshot testing easier 😅

File: modules/effects/migrations/18_0_0-beta/index.ts [hunk 2]
```diff
@@ -14,29 +14,47 @@ import {
...
           }
         })
-        .find(Boolean);
+        .filter(Boolean);
+
+      if (effectsImportsAndDeclarations.length === 0) {
+        return;
+      } else if (effectsImportsAndDeclarations.length > 1) {
+        ctx.logger.warn(
+          '[@ngrx/effects] Skipping because of multiple `concatLatestFrom` imports'
```
Comment (timdeschryver) [inline modules/effects/migrations/18_0_0-beta/index.ts:52]: Do we have to log this?
Or maybe change this to an info message because no action is required here.

File: modules/effects/migrations/18_0_0-beta/index.ts [hunk 3]
```diff
@@ -53,6 +71,7 @@ export function migrateConcatLatestFromImport(): Rule {
         .map((element) => element.name.getText())
         .join(', ');
 
+      const changes: Change[] = [];
```
Comment (timdeschryver) [inline modules/effects/migrations/18_0_0-beta/index.ts:74]: If I understand correctly this is the "real" fix as we're creating a new collection for each file, correct?

Comment (rainerhahnekamp) [reply modules/effects/migrations/18_0_0-beta/index.ts:74]: Exactly, that's the main one. I see the others as edge cases.

File: modules/effects/migrations/18_0_0-beta/index.ts (hunk 1 above)
Comment (rainerhahnekamp) [reply modules/effects/migrations/18_0_0-beta/index.ts]: Done

File: modules/effects/migrations/18_0_0-beta/index.ts (hunk 2 above)
Comment (rainerhahnekamp) [reply modules/effects/migrations/18_0_0-beta/index.ts:51]: Changed it to info. Maybe it is good to keep it so that devs are aware of it.

**Comment by rainerhahnekamp** [comment]
@timdeschryver I've applied the requested changes. I will do the same for the PR regarding the component store.

**Review by timdeschryver — APPROVED** [review]
👍

**Review by brandonroberts — APPROVED** [review]
