### PR TITLE
fix(signals): enable `withProps` to handle Symbols

### LINKED ISSUE #4655: `withProps` doesn't allow Symbols as keys
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

`signalStore` skips any symbols of `withProps`.

In this example, `secret` is undefined

```typescript
const SECRET = Symbol('SECRET');

const Store = signalStore(withProps(() => ({ [SECRET]: 'secret' })));

@Component({
  selector: 'app-root',
  template: `Secret: {{ secret }}`,
  providers: [Store],
})
export class App {
  protected store = inject(Store);
  protected secret = this.store[SECRET];
}
```

https://stackblitz.com/edit/github-wnvurbbx?file=src%2Fmain.ts

### Expected behavior

Symbols should be used as well

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx 19, Angular 19

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by rainerhahnekamp**
Resolve an issue in `signalStore` that prevented Symbols from being added as property keys when merging
different features.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

The value is just undefined.

Closes #4655

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

File: modules/signals/src/signal-store.ts [hunk 1]
```diff
@@ -1355,12 +1355,18 @@ export function signalStore(
...
+        ...props,
+        ...methods,
+      };
 
       (this as any)[STATE_SOURCE] = innerStore[STATE_SOURCE];
 
-      for (const key in storeMembers) {
-        (this as any)[key] = storeMembers[key];
+      for (const key of Reflect.ownKeys(storeMembers)) {
+        if (typeof key === 'string' || typeof key === 'symbol') {
```
Comment (timdeschryver) [inline modules/signals/src/signal-store.ts:1367]: Can we also include `number`s?
Because these can also be used as property names.

Or maybe this isn't a problem?

Comment (rainerhahnekamp) [reply modules/signals/src/signal-store.ts:1367]: Short answer: No, and I've added a test as well.

In my understanding, numbers are always serialized during the runtime. That's why Reflect.ownKeys returns 'symbol | string`.

Example

```typescript
const o = {1: 'a'}
o[1]; // returns 'a'
o['1']; // returns 'a'
```

The if condition was necessary because of the TypeScript compiler. It doesn't accept a union type.

**Review by timdeschryver — APPROVED** [review]

File: modules/signals/src/signal-store.ts [hunk 2]
```diff
@@ -1355,12 +1355,18 @@ export function signalStore(
...
+          (this as any)[key] = storeMembers[key];
+        }
```
Comment (markostanimirovic) [inline modules/signals/src/signal-store.ts:1369]: what's the reason for adding this `if`? is there any other type of key other than string or symbol that should be ignored?
```suggestion
        (this as any)[key] = storeMembers[key];
```

**Review by markostanimirovic — CHANGES_REQUESTED** [review]

File: modules/signals/src/signal-store.ts (hunk 2 above)
Comment (rainerhahnekamp) [reply modules/signals/src/signal-store.ts:1369]: `key` in this case is of type `string | symbol` and TypeScript doesn't allow an access with that type. That's why I had to apply type narrowing.

Litte bit strange, since I've never experienced that before.

Comment (markostanimirovic) [reply modules/signals/src/signal-store.ts:1369]: I just checked and it seems to work on my machine 😅 



Anyway, instead of adding additional LOC that will end up in the final bundle unnecessarily in order to satisfy TS, I suggest using type casting if it doesn't work without `if (typeof key === 'string' ...`

File: modules/signals/spec/with-props.spec.ts [hunk 3]
```diff
@@ -47,4 +48,24 @@ describe('withProps', () => {
...
+  });
+
+  it('allows numbers as props', () => {
+    const Store = signalStore(withProps(() => ({ 1: 'Number One' })));
+    const store = TestBed.configureTestingModule({ providers: [Store] }).inject(
+      Store
+    );
+
+    expect(store[1]).toBe('Number One');
+  });
```
[the remark this answers is not in the document]
Comment (rainerhahnekamp) [reply modules/signals/spec/with-props.spec.ts]: @markostanimirovic. I've integrated the support for symbol in the following areas:
- `withState`
- `withMethods`
- `withComputed`
- Slices (`DeepSignal`)
- `deepFreeze`
- override protection

Think, I've covered them all.

File: modules/signals/src/signal-store-models.ts [hunk 4]
```diff
@@ -11,9 +11,9 @@ export type StateSignals<State> = IsKnownRecord<Prettify<State>> extends true
     }
   : {};
 
-export type SignalsDictionary = Record<string, Signal<unknown>>;
+export type SignalsDictionary = Record<string | symbol, Signal<unknown>>;
```
Comment (rainerhahnekamp) [inline modules/signals/src/signal-store-models.ts:14]: @markostanimirovic @timdeschryver: This could be seen as a breaking change.

If I leave it to string only (`SignalsDictionary` & `MethodsDictionary`), tests and build would also be successful.

What's your take on this?

Comment (rainerhahnekamp) [reply modules/signals/src/signal-store-models.ts:14]: @timdeschryver honestly, I have no idea. I just saw that this is a change to public type, and we don't know if there is some code out there that depends, that it is only a string and nothing else...

Comment (markostanimirovic) [reply modules/signals/src/signal-store-models.ts:14]: Since `Record<string, ...>` already supports symbols as keys, we can avoid changing `SignalsDictionary` and `MethodsDictionary` types just in case.

Comment (rainerhahnekamp) [reply modules/signals/src/signal-store-models.ts]: Done

**Review by timdeschryver — APPROVED** [review]
