### PR TITLE
bug(store) add explicit overloads for createSelector

### LINKED ISSUE #3268: Type inference for createSelector is broken since changing to variadic tuple types
## Minimal reproduction of the bug/regression with instructions:

```
const state: {first : string} = { first: 'state' };

const getData = <T>(d: T): T => d;
const returnState = () => state;

const selector = createSelector(returnState, getData);
expect(selector(state).first).toEqual('state');

```

As of v13 above code will give a compile error saying: Object is of type 'unknown'.

## Expected behavior:

Expected that createSelector would be able to infer the return type for `selector` correctly to `{first : string}`

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx 13

### PR DESCRIPTION
**Pull request by david-shortman**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #3268

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

I only added explicit overloads for `createSelector` with variadic "slice" arguments, because only that signature failed due to the problems identified in #3268. The signature that uses an array for the "slices" [does not fail](https://www.typescriptlang.org/play?jsx=0#code/C4TwDgpgBAyhA2EDGwD2AnAPAFQDRQDUA+KAXigAoBnYAQ2AgC4psBKMkggbgFgAoUJCgBZCAFtUASwBeEACZxEKDDnzEysBMjRY8hIrz785yeLXTQAZgFcAdikmpbUJBfoRF2lTDoN8MeEkkCCooCAAPBls5ULsAa1tUAHdbAG0AXXwAJRDreGAiCn4oKCotZXQqZk8KzB93fHjElKIMqAAyYpKoVIA6foBvHskoSWc4iBBUS1hA4Kp06vKdOt8IfzmQ1Ml0kgBfTK6wdFQAKy90Zgp+3qrZoJD2UhIcqjzgflZmUQkZeRqVvU-FBXu8DPx+EgnDRSmtmANLJJKsAoMwAOQ0dxovYaIaI5HozEMNFQPaGSHQlEAcwgwAAIvRaBocIU5Mw2OyOFA5IYobYYRZgNZ0LYgdByBQniQiRByXw+TCykodBpXBB3ACMBRUoLhaK1pkoDT6YzWHKFSj8TRCWsSeQlRdqGtWL0rcBDEA).

### CODE REVIEW

File: modules/store/src/selector.ts [hunk 1]
```diff
@@ -122,11 +122,81 @@ export function defaultMemoize(
...
+): MemoizedSelector<State, Result>;
+
 export function createSelector<State, Slices extends unknown[], Result>(
-  ...args: [...Selector<State, unknown>[], unknown] &
+  ...args: [...slices: Selector<State, unknown>[], projector: unknown] &
     [
-      ...{ [i in keyof Slices]: Selector<State, Slices[i]> },
-      (...s: Slices) => Result
+      ...slices: { [i in keyof Slices]: Selector<State, Slices[i]> },
+      projector: (...s: Slices) => Result
```
Comment (david-shortman) [inline modules/store/src/selector.ts:199]: I added names to clarify what these tuples represented.

Comment (timdeschryver) [reply modules/store/src/selector.ts:199]: Nice, I didn't know we could do that! 🤩

**Comment by david-shortman** [comment]
> It seems like the case of the issue isn't resolved with this fix, but I can't figure out how to do it otherwise... This should cover most of the cases imo, which is better than nothing.

This appears to verify that the case presented in the issue works: [playground](https://www.typescriptlang.org/play?jsx=0#code/C4TwDgpgBAyhA2EDGwD2AnAPAFQDRQDUA+KAXigAoBnYAQ2AgC4psBKMkggbgFgAoUJCgBZCAFtUASwBeEACZxEKDDnzEysBMjRY8hIrz785yeLXTQAZgFcAdikmpbUJBfoRF2lTDoN8MAEZ8ACUIKmt4YCIKfigoKgDmT2UsH3d-AKJcWKgwdFQAKy90ZmpE2AD2UhJQ8Mj+VmZRCRl5ZJ1MNL8oWoiowxMkMwsoG3tgR2dXCHd2718IDP8AJhCwvuichKStFM6FjKyt5Z2lDq7F2GWjvji8wuLS7Yr8KhOrqpr1+r5GkXEpLIFLtzgcet9+sZTOYrHYHE4XG4GHNUmDAit-ABmNZ1KIxW7xcoo-bpCo3OJvU7FEndGDXbIEqiYql7C5Y8m5fJFFJPIlBeLvOmvZmwTGfcG4hpNAGtYFneak3qRAxQoYw0ZwiYI6azEEK2n8oWi-wAFhxG3xFKJetRpMCHMpmnlttp9K2IuJbNFDpNLNBdpNHPu3J0vKS-MdRqZSWx8V9sBN4qVwCl-xaQM9YOTKr4g2GsPGk0RM2RNppl3RVyxpv8AFZzcrLYS-fqK5kGRTBWWvXSHR7u2jMT6Wy6K4GO-FayPy3Wg1zHpRnpXI6t4h7Y1R4zAzZOkrWkxDU81AW0B4qITm8+qxvCpkiPGeDRjjQm6-4AGwNvFba3OmdkidI0fCs3UZfs-x7IdAK3YDTQdKcnWpHtawdd9px7d85weHlFz5V5BVXaMX03JIdyoBCYHreI0Ngd8D0lX5pXTU8IKzC8BmhEYby1O8SwfVi7UNVcYFjbc31o-wAHYv02RlfyQtF22OdC0VAilwIUu0oK2GCBNpcctgo2DYBQwCaMzO1MMAySVLtSSsJDDAwxeAUkkI9dXi3MiKKoqhzM-eIbNgST6L6I8ZQzYzsw4tUuM1IsdVLPS22fESaxMj8pP8AAOGSmyXYz7UArtkpWPtbNpbTGV0zT9PgiqK1MrZzMKqytiCizaXswDsoanKHIXJsrXDCdOzc0a1xjCaSNfHIKR86b-OmjrpLm+JetgbKclCn4-mPWVOsuaL+FVfMNULbV70O-x4EkJAwigCAAA8GFsOQqCgOwAGtbFQAB3WwAG0AF08pyAA6SHzAAcyoZhAch8GqFu+64cQ1kwW+36AaIEH8GDBcsf+2xgagAAyNbAbWuJEeRu6wmYABvKBAckKBJGcL6IBAVBLFgFGwmBvr+fpqhWeBkgAF8JrueccIoWmkgFqgdpTAk4mB8LmLlWqjvYk6+CQJwaHiBYmcsSR0BN5gAHIaHcG3JY0ZmLat4BbfthgbagSXDH4I3bBN6GIGAAARehaA0HBojkZg2DjjgoDkQwA5NixgGsdBbAuDQKHFT2ID9w3jeAeIbQ0RL+OKCh08z7OwWDsOI9YIvU9L12aA9hZvfIKgbWoBZWHBjvgEMIA).

**Comment by david-shortman** [comment]
> Also, would it be possible to move the tuple version to the top and add a `@deprecated` annotation to the re-added selectors? This seems fine for the selectors in the example app but since I don't have a reproduction of the issue, I can't confirm that this works correctly for the deprecated cases.

The order cannot be changed, as then the variadic signature will always match. This error is demonstrated in this [playground](https://www.typescriptlang.org/play?jsx=0#code/C4TwDgpgBAyhA2EDGwD2AnAPAFQDRQDUA+KAXigAoBnYAQ2AgC4psBKMkggbgFgAoUJCgBZCAFtUASwBeEACZxEKDDnzEysBMjRY8hIrz79+c5PFrpoAMwCuAOxSTUdqEkv0Ii7Sph0G+GHhJJAgqKAgADwY7OTD7AGs7VAB3OwBtAF18ACVQm3hgIgp+KCgAOgqLAHMqZjSKsqogkNrNJR1MXw98BKTUokz8MHRUACtvdGZelLsMqAAyEtKoNKXl8oqm4NDmAG8VyShJF3iIEFQrWGbQjOYvZSwu-yvtqjTJDJIAX1w15eGxhNmBQGq1Aq92KQSLkqPlgH8MvxWMxRBIZPJ7h0nhAcnkCgZjHxTEhzJYoLYHMAnC43BAPJifH4cbAAIy42H44p8UpUFl3LQPTpMgIsoi-blQAHjB7A3l3FmQ6F4+F8ZEicRSWQKAVY4VQGFwglEswWaz2RzOVzuBgMx56mBs2AAJnZhq5PL5bQmQu6rLFSyoTv57UZvpgTv9EqlQMoctZ+EDdydiv1yqRKI16O1IbtvoN+MMxNJZsp1KtdJtOtDzwdARdsAAzK7OQHPbafTXReKeUGvYLsXXIzyG8HvQPG0PJSNpTpZW3HYnnQmR42U-mVWrUZqMVXc8910ai6byeaqZbafTdx3mbWl42AgAWZuFd1QOPt8cOyeLj-2iPdt8V1-MMG2-B9R37e0H0naMZVjecE17cNlzuJs33A2AHzXNNVQzNEtWA-dlUPE0yQpC0aWtTwr0-R1kPvTCAgAVmfIpWwg3Uwy7AMkJov9vyAviQLAjjqxvaCAKoJjRL3G8mJg6cY2oBC3yQ+sqCAtCqAwmAnzfaTYCY7COQ3PDt2zMc9QPQtSJLCjy0vHNrxFOsAjQ3TmICAA2VjX3fITO2-XinM-f8A0EkL7VAySdIC8TvwMwi5O-LyZOc2AvIUwE4OU+VEKTFCGO0u49Kku4WLfVKMuMuF03VfCd0ivNiJsklj3Is9KIraims7VyGI8wzvICAB2Xz2L7TjAsk4LLLDMKJQ0tLP2igNYt6+LJMSuLmJS5b7UyySRv2sMRqymcMDnPLVIKwDUITHTSsSiqqCqmAfLfY7YBGmqCjqrcsyS1jWuLE9S3PKigfjO8YHcvSYAq97RoCAAOcbFrbHa-Rmk6awW4dcZvVbFvWuaawkgNto23bJLerH3u-L6oZgM7JJRwnUfOpS-nfNkebUgCCfvHnHsF-TyrF167h8nmmbGnn2dgFGll+0z6vMqHrMJJBnBoN8mT2KxJHQPXmAAchoDwza+DR9iNk3gHNy2GDNqAvkMfgdbsPWqggYAABF6FoDQcCKORmDYCOOCgORDC9vXLGAGx0DsbENAoFNnYgD2+Hj4A313DQL0rHMKET5PU71X2A6D1gc7z8ljZoJ2mVd8gqF3agmVYMp7ZoQwgA).

File: modules/store/src/selector.ts (hunk 1 above)
Comment (david-shortman) [reply modules/store/src/selector.ts:199]: It's quite handy bc variadic tuple types become quite cumbersome looking quickly 😅

**Comment by mattlewis92** [comment]
> @mattlewis92 would it be possible if you confirm this fix in your repo?

Sure thing, I just checked it in our repo with this change and it now all builds correctly! 🙌

**Review by timdeschryver — APPROVED** [review]
Thanks @david-shortman , and also thanks @mattlewis92 for the verification.

**Review by brandonroberts — APPROVED** [review]
