### PR TITLE
fix(store): allow a generic reducer

### LINKED ISSUE #2982: Support generic state
Since this change [pull/2967](https://github.com/ngrx/platform/pull/2967/files#diff-b5b61b5c88ce4368769a58df0918602484c6c507e6a6dfad51e4746e470caf26) Typescript can't compile my reducer based on generic state.

The following error is being generated:
_Argument of type '(state: TState, action: object & { type: string; }) => TState' is not assignable to parameter of type 'OnReducer<TState, [ActionCreator<string, Creator<any[], object>>]>'.
 Type 'TState' is not assignable to type 'TState extends object ? { [P in keyof TState]: TState[P]; } : TState'.
 Type 'object' is not assignable to type 'TState extends object ? { [P in keyof TState]: TState[P]; } : TState'.(2345)_
 
## Minimal reproduction of the bug/regression with instructions:
Reproduction in the [Typescript playground](https://www.typescriptlang.org/play?noUnusedLocals=true&noUnusedParameters=true&ts=4.2.3#code/JYWwDg9gTgLgBAbzgQQMY2BAdgYSgUwEMZoAaFdTLAJXwBMBXVfKc1A4-Wx51ubAL5wAZlAgg4AcgACWAOZQAHgHoAziQKSA3ACgdqbOrjsiGuAF44WBgBsbcQqrgMsAaywQA7lgdO0GbDxTaF0dfEVIWBEXSmxjDhh8AHF8LBZgVG4mFgAeABUAZRhOOHDErDonCAAjACt8dAA+AApgLGAMQhsizgAuOELixIBKfv8qLN58nsTGxB04Y0N4Ah4WC3jTLnpsqGaFxbg2juAumfxSA8XsZpNiMjhm9U5yQlisYYs5hCvD5QAqf6-Q7-FBQOQMECpeAQYRwGAATzA+CkTyG+H6gxeDne-Rq9XQcAAZIh4UiMXB1FA2nItHABJ9zHMsYlJEcnB54I5VMA5FhCNUbCiSHAwIQoIQoYkoPw4YjkVIAPI0HZTFkXOAAbXGgQS0ByVJp5CC9ygOUIWARmoAuuR8Q0YI1GtbGpIAHTAxagvLkqTqtnADkQLmqHl8gVC+EQMkKyTq0qKcqVfh1B1wAD8pM1AAUjj5XPgEbCBudrZjzjnrXShOX0e7PXBvb7JPb0AGgyGw-zBcLo-KUXHzgmk1VU4TM0gc3m4AWi3D1WWS+jK9W4LXOO7mgAmADMABYAKzDBv-ZSeggwBhQHzPRJwXSHenHxbDUKLC9XnyrXa6ARAA).

## Describe any alternatives/workarounds you're currently using
I am currently casting the state returned by the reducer to 'any'.

## If accepted, I would be willing to submit a PR for this feature

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[X ] No

### PR DESCRIPTION
**Pull request by timdeschryver**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #2982

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

While this works, I can't explain why ...😅

### CODE REVIEW

**Comment by alex-okrushko** [comment]
> while this works, I can't explain why ...😅

😂😂😂

File: modules/store/src/reducer_creator.ts [hunk 1]
```diff
@@ -42,11 +40,14 @@ export interface OnReducer<State, Creators extends readonly ActionCreator[]> {
...
-  ...args: [...creators: Creators, reducer: OnReducer<State, Creators>]
+  ...args: [
+    ...creators: Creators,
+    reducer: OnReducer<State extends infer S ? S : never, Creators>
+  ]
 ): ReducerTypes<State, Creators> {
   // This could be refactored when TS releases the version with this fix:
   // https://github.com/microsoft/TypeScript/pull/41544
-  const reducer = args.pop() as OnReducer<State, Creators>;
+  const reducer = args.pop() as OnReducer<any, Creators>;
```
Comment (alex-okrushko) [inline modules/store/src/reducer_creator.ts:50]:
```suggestion
  const reducer = args.pop() as OnReducer<unknown, Creators>;
```
Would that still work? 🙂

**Review by alex-okrushko — APPROVED** [review]

**Review by brandonroberts — APPROVED** [review]
