### PR TITLE
fix/feat(store): createReducer: on should not be overwritten

### LINKED ISSUE #1956: Docs: Add more explanation that you can only have one distinct action type per on function with createReducer
It is possible to have 2 effects looking at one action. But it seems impossible to have 2 `ons` looking at one action.

https://github.com/ngrx/platform/blob/b07ae4ee835cbc2e9ac9a923c46ca64966c75270/modules/store/src/reducer_creator.ts#L189

It is not obvious and it will override my previous action reducer.

After thinking about it, a selector combining 2 variables will do the job, but it's just not obvious and it does fail quite silently!

### PR DESCRIPTION
**Pull request by zhaosiyang**
createReducer should allow ons to take actions of same type and excute all ons to match the action dispatched

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
If the following is configured and initial state is 0, if `increase` action is dispatched, the next state is 2, because the the second `on` has same action type as the first `on`, and the first `on` is overwritten.
```
const increase = createAction('[COUNTER] INCREASE');
createReducer(0, on(increase, state = state + 1), on(increase, state = state + 2))
```

(Indirectly) Closes #1956 

## What is the new behavior?
In `createReducer`, `on` should not overwrite previous `on`s if they have the same action types.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by zhaosiyang** [comment]
I have added an example of the necessity of this behaviour here (https://github.com/ngrx/platform/issues/1956#issuecomment-526720340)

**Comment by timdeschryver** [comment]
I'm not sure if this is a "bug".
I think both options are viable, and we'll have to decide which behavior makes the most sense and is safest to use.

**Comment by zhaosiyang** [comment]
> I'm not sure if this is a "bug".
> I think both options are viable, and we'll have to decide which behavior makes the most sense and is safest to use.

Yeah, it could be either feature or bug. 

In my opinion, the `on` should simply mean "execute this function when this action is dispatched" regardless of any other settings. We thus decoupled `on`s in this way.

Some usage case for justifying this feature could be:
1. Update some state (that I defined) whenever some library-defined action is dispatched, for example (`@ngrx/store/init`, `'@ngrx/store/update-reducers` )
2. Create higher order reducers which inject some global `on`s: please see https://github.com/ngrx/platform/issues/1956#issuecomment-526720340 for more detail

However, I can't think of any case that need to overwrite previous `on` if action type is the same.

File: modules/store/src/reducer_creator.ts [hunk 1]
```diff
@@ -229,15 +229,25 @@ export function createReducer<S, A extends Action = Action>(
   initialState: S,
   ...ons: On<S>[]
 ): ActionReducer<S, A> {
-  const map = new Map<string, ActionReducer<S, A>>();
+  const map = new Map<string, ActionReducer<S, A>[]>();
   for (let on of ons) {
     for (let type of on.types) {
-      map.set(type, on.reducer);
+      if (map.has(type)) {
```
Comment (MikeRyanDev) [inline modules/store/src/reducer_creator.ts]: You could do the composition on the fly here instead of storing arrays for a small perf bump in the generated reducer:

```ts
if (map.has(type)) {
  const reducer = map.get(type) as ActionReducer<S, A>;
  map.set(type, (state, action) => on.reducer(reducer(state, action), action);
}
else {
  map.set(type, on.reducer);
}
```

Comment (zhaosiyang) [reply modules/store/src/reducer_creator.ts]: Thanks @MikeRyanDev for the great suggestion. I have pushed a commit. :)

**Comment by brandonroberts** [comment]
@timdeschryver you have anymore thoughts on this?
