### PR TITLE
fix(component): use setTimeout instead of requestAnimationFrame in SSR mode

### LINKED ISSUE #4902: @ngrx/component does not work in SSR + zoneless
### Which @ngrx/* package(s) are the source of the bug?

component

### Minimal reproduction of the bug/regression with instructions

When using ngrxLet in a angular app with both SSR and zoneless, you're faced with an error:

uncaughtException ReferenceError: requestAnimationFrame is not defined.

I made a quick example:
https://github.com/JelleBruisten/ngrxlet-zoneless-ssr

It looks like due that when zoneless we use the AnimationFrameTickScheduler
```ts
@Injectable({
  providedIn: 'root',
  useFactory: () => {
    const zone = inject(NgZone);
    return isNgZone(zone)
      ? new NoopTickScheduler()
      : inject(AnimationFrameTickScheduler);
  },
})
export abstract class TickScheduler {
  abstract schedule(): void;
}
```

And within AnimationFrameTickScheduler we use this, but requestAnimationFrame does not exist in node during the server render:

```ts
  schedule(): void {
    if (!this.isScheduled) {
      this.isScheduled = true;
      requestAnimationFrame(() => {
        this.appRef.tick();
        this.isScheduled = false;
      });
    }
  }
```

We're throwing an error

### Expected behavior

To schedule using a different mechanism maybe setTimeout while on server?

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

ngrx: 19.2.1 ( did try it with latest 20.0.0-rc... )
angular: v20

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by JelleBruisten**
…stead of requestAnimationFrame

## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[X] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

When using either ngrxLet or ngrxPush in ssr and zoneless, the server calls `requestAnimationFrame` which does not exist in a node environment. 

Closes #4902

## What is the new behavior?

Within a node environment ( ssr ) and zoneless we use setTimeout instead of requestAnimationFrame.

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

## Other information
I did some more testing on angular v20, when using ssr + zoneless and using a `NoopTickScheduler` it does trigger changes. I opted for not removing the `NoopTickScheduler` and making big changes since `@ngrx/component` is in maintenance mode.

### CODE REVIEW

File: modules/component/src/core/tick-scheduler.ts [hunk 1]
```diff
@@ -19,6 +25,7 @@ export abstract class TickScheduler {
 })
 export class AnimationFrameTickScheduler extends TickScheduler {
   private isScheduled = false;
+  private isServer = inject(PLATFORM_ID);
```
Comment (markostanimirovic) [inline modules/component/src/core/tick-scheduler.ts]: This will not work. `isServer` will always be `true`. It's necessary to use `isPlatformServer`:

```ts
private readonly platformId = inject(PLATFORM_ID);
private readonly isServer = isPlatformServer(this.platformId);
```

File: modules/component/src/core/tick-scheduler.ts [hunk 2]
```diff
@@ -19,6 +25,7 @@ export abstract class TickScheduler {
 })
 export class AnimationFrameTickScheduler extends TickScheduler {
```
Comment (markostanimirovic) [inline modules/component/src/core/tick-scheduler.ts]: This is a private API, so we can rename it properly:

```suggestion
export class ZonelessTickScheduler extends TickScheduler {
```

File: modules/component/src/core/tick-scheduler.ts [hunk 3]
```diff
@@ -19,6 +25,7 @@ export abstract class TickScheduler {
...
   private isScheduled = false;
+  private isServer = inject(PLATFORM_ID);
 
   constructor(private readonly appRef: ApplicationRef) {
```
Comment (markostanimirovic) [inline modules/component/src/core/tick-scheduler.ts]: let's use either constructor-based DI or `inject` function, but not both.

File: modules/component/src/core/tick-scheduler.ts [hunk 4]
```diff
@@ -27,10 +34,18 @@ export class AnimationFrameTickScheduler extends TickScheduler {
...
+        requestAnimationFrame(() => {
+          this.appRef.tick();
+          this.isScheduled = false;
+        });
+      } else {
+        setTimeout(() => {
+          this.appRef.tick();
+          this.isScheduled = false;
+        });
+      }
```
Comment (markostanimirovic) [inline modules/component/src/core/tick-scheduler.ts]: There is no need to fully duplicate logic. Also, the condition has to be reversed - `requestAnimationFrame` should be used when `isServer` is `false`, not `true`:

1. Add a class member:

```ts
private readonly scheduleFn = this.isServer ? setTimeout : requestAnimationFrame;
```

2. Then use `scheduleFn` within the `schedule` method:

```suggestion
      scheduleFn(() => {
        this.appRef.tick();
        this.isScheduled = false;
      });
```

**Review by markostanimirovic — CHANGES_REQUESTED** [review]
Thanks for the PR @JelleBruisten! See the requested changes below.

It's also necessary to add a unit test and verify the fix.

**Comment by markostanimirovic** [comment]
@JelleBruisten target branch has to be `main`, not `master`.

**Comment by JelleBruisten** [comment]
@markostanimirovic I rebased the branch from the main branch.

**Review by markostanimirovic — APPROVED** [review]

**Review by rainerhahnekamp — APPROVED** [review]

File: modules/component/src/core/tick-scheduler.ts [hunk 5]
```diff
@@ -17,17 +24,19 @@ export abstract class TickScheduler {
...
   providedIn: 'root',
 })
-export class AnimationFrameTickScheduler extends TickScheduler {
+export class ZonelessTickScheduler extends TickScheduler {
+  private readonly appRef = inject(ApplicationRef);
+  private readonly platformId = inject(PLATFORM_ID);
+  private readonly isServer = isPlatformServer(this.platformId);
+  private readonly scheduleFn = this.isServer
+    ? setTimeout
+    : requestAnimationFrame;
```
Comment (hakimio) [inline modules/component/src/core/tick-scheduler.ts:33]: @JelleBruisten this change introduced `Illegal invocation` error #5108
