### PR TITLE
fix(component-store): use asapScheduler to schedule lifecycle hooks check

### LINKED ISSUE #3573: Error: 1 periodic timer(s) still in the queue when testing a store with fakeAsync
### Which @ngrx/* package(s) are the source of the bug?

component-store

### Minimal reproduction of the bug/regression with instructions

```
it("doesn't work", fakeAsync(() => {
  new ComponentStore<{}>();
  expect(1).toEqual(1);
}));
```
Running this unit test produces
> Error: 1 periodic timer(s) still in the queue.

### Minimal reproduction of the bug/regression with instructions

The test above should pass.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 14.0.2
Angular: 14.2

### Other information

I believe it's a regression introduced with the lifecycle hooks. In particular, the run-time check in this PR: https://github.com/ngrx/platform/pull/3432/files#diff-dd156bfdaf294eb2eb0c9c87e1403ddd40190b88afa6ed8b443fb7cb1cd008f6R322

This check uses rxjs `asyncScheduler.schedule()`, which internally uses `setInterval` - a periodic task that offends `fakeAsync` :)
https://github.com/ReactiveX/rxjs/blob/6.x/src/internal/scheduler/AsyncAction.ts#L50

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by amakhrov**
Switch from asyncScheduler to asapScheduler to prevent the "1 periodic timer(s) still in the queue" error.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
  there are existing tests for this that still pass
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #3573

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

File: modules/component-store/src/component-store.ts [hunk 1]
```diff
@@ -322,7 +322,7 @@ export class ComponentStore<T extends object> implements OnDestroy {
    * but not used with provideComponentStore()
    */
   private checkProviderForHooks() {
-    asyncScheduler.schedule(() => {
+    asapScheduler.schedule(() => {
       if (
         isDevMode() &&
```
Comment (amakhrov) [inline modules/component-store/src/component-store.ts:327]: Additionally, I'm wondering whether the `isDevMode()` check should be perform at the very beginning, guarding the full `asapScheduler.schedule` call, instead of just scheduled callback body

Comment (brandonroberts) [reply modules/component-store/src/component-store.ts:327]: I tried using `isDevMode()` outside the callback body, and it doesn't work as intended.

**Comment by markostanimirovic** [comment]
I renamed the PR title to avoid potential confusion because we can use ComponentStore within the `fakeAsync`, but we need to add at least one `tick` that will flush scheduled macrotasks:

```ts
it('works before changes from this PR', fakeAsync(() => {
  new ComponentStore();
  tick(0);
}); // no error
```

File: modules/component-store/src/component-store.ts [hunk 2]
```diff
@@ -322,7 +322,7 @@ export class ComponentStore<T extends object> implements OnDestroy {
    * but not used with provideComponentStore()
    */
   private checkProviderForHooks() {
-    asyncScheduler.schedule(() => {
+    asapScheduler.schedule(() => {
```
Comment (markostanimirovic) [inline modules/component-store/src/component-store.ts:325]: Thanks for the PR, @amakhrov! Can you add a unit test that verifies that there is no error?

**Review by markostanimirovic — CHANGES_REQUESTED** [review]

File: modules/component-store/src/component-store.ts (hunk 2 above)
Comment (amakhrov) [reply modules/component-store/src/component-store.ts:325]: what if I just change `tick(0)` to `flushMicrotasks()` in the existin tests (there are 2 of them for the hooks feature).

Comment (markostanimirovic) [reply modules/component-store/src/component-store.ts:325]: sounds good 👍

**Review by markostanimirovic — APPROVED** [review]

File: modules/component-store/src/component-store.ts (hunk 2 above)
Comment (aokrushk) [reply modules/component-store/src/component-store.ts:325]: @timdeschryver It's hard to test for that. I'd say the `flushMicrotasks();` change in unit tests is the one that "reproduces" the issue.

**Review by aokrushk — APPROVED** [review]

**Review by timdeschryver — APPROVED** [review]
