### PR TITLE
fix(router-store): cast return type as RouterReducerState

### LINKED ISSUE #2882: Type 'unknown' is not assignable to type 'RouterReducerState<SerializedRouterStateSnapshot>
`Error: src/app/app.module.ts:31:26 - error TS2322: Type '<T extends BaseRouterStoreState = SerializedRouterStateSnapshot>(state: RouterReducerState<T> | undefined, action: Action) => RouterReducerState<...>' is not assignable to type 'ActionReducer<unknown, Action>'.
  Types of parameters 'state' and 'state' are incompatible.
    Type 'unknown' is not assignable to type 'RouterReducerState<SerializedRouterStateSnapshot> | undefined'.
      Type 'unknown' is not assignable to type 'RouterReducerState<SerializedRouterStateSnapshot>'.

31     StoreModule.forRoot({router: routerReducer, count: counterReducer, movies: movieReducer, }),
                            ~~~~~~



`



`
    StoreModule.forRoot({router: routerReducer, count: counterReducer, movies: movieReducer, }),`

An error occurred when routerReducer and counterReducer are referenced together

No error will be reported if routerReducer is used alone

### PR DESCRIPTION
**Pull request by timdeschryver**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #2882

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Review by brandonroberts — APPROVED** [review]

File: modules/router-store/src/reducer.ts [hunk 1]
```diff
@@ -16,22 +16,20 @@ export type RouterReducerState<
 };
 
 export function routerReducer<
-  T extends BaseRouterStoreState = SerializedRouterStateSnapshot
->(
-  state: RouterReducerState<T> | undefined,
-  action: Action
-): RouterReducerState<T> {
+  RouterState extends BaseRouterStoreState = SerializedRouterStateSnapshot,
+  Result = RouterReducerState<RouterState>
```
Comment (alex-okrushko) [inline modules/router-store/src/reducer.ts:20]: Should the `Result` extend `RouterReducerState`? Otherwise anything could be pushed into in.
```suggestion
  Result extends RouterReducerState<RouterState> = RouterReducerState<RouterState>
```

**Review by alex-okrushko — APPROVED** [review]
