### PR TITLE
fix(RouterStore): serialize routeConfig inside the default serializer

### LINKED ISSUE #1363: DefaultRouterStateSerializer: path property missing in routeConfig
## Minimal reproduction of the bug/regression with instructions:

Example: https://stackblitz.com/edit/ngrx-seed-nl8b8q?file=src%2Fapp%2Fapp-routing.module.ts

Routing effect based on: https://github.com/vsavkin/state_management_ngrx4

## Expected behavior:

routerConfig should contain path / pathMatch (if it exists in original routerConfig) to allow easy identification of Router rule that was used to match used route. This way of matching is used in above mentioned example.

In example above, if routes in `app-routing.module.ts` are defined as shown in example, it's not possible to distinguish in `effects/routing.effects.ts`, function `handleNavigation` what rule in router definition was used (`data/:id` or `test/:id`) since path / pathMatch keys are missing. This has worked before since routeConfig from ActivatedRouteSnapshot was used directly and it contains these keys.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 6.1.0
Angular: 6.1.1
Node: 8.9.4

## Other information:
Current behaviour is caused by: https://github.com/TypescriptID/platform/pull/102/commits/7917a276fa199b19d6d8f2e3d2fa1708e3481c2b

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[x] No

### PR DESCRIPTION
**Pull request by timdeschryver**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
The `routeConfig` isn't being serialized in `DefaultRouterStateSerializer`.

Issue Number: #1363

## What is the new behavior?
The `routeConfig` is being serialized in `DefaultRouterStateSerializer`.
Note that not all properies are being serialized:

```ts
{
    // was already being serialized
    component?: Type<any>;

	// added properties to be serialized
    path?: string;
    pathMatch?: string;   
    redirectTo?: string;
    outlet?: string;

    // not being serialized
    matcher?: UrlMatcher;  
    canActivate?: any[];
    canActivateChild?: any[];
    canDeactivate?: any[];
    canLoad?: any[];
    data?: Data;
    resolve?: ResolveData;
    children?: Routes;
    loadChildren?: LoadChildren;
    runGuardsAndResolvers?: RunGuardsAndResolvers;
}
```

## Does this PR introduce a breaking change?

```
[x] Yes
[ ] No
```

The default router serializer now returns a `null` value for `routeConfig` when `routeConfig` doesn't exist on the `ActivatedRouteSnapshot` instead of an empty object.
 BEFORE:
 ```json
{
  "routeConfig": {}
}
```
 AFTER:
 ```json
{
  "routeConfig": null
}
```

## Other information
If this doesn't belong in the default serializer, feel free to close.
It's always possible for the impacted users to create there own serializer.

Closes #1363

### CODE REVIEW

File: modules/router-store/src/serializer.ts [hunk 1]
```diff
@@ -39,9 +39,15 @@ export class DefaultRouterStateSerializer
       data: route.data,
       url: route.url,
       outlet: route.outlet,
-      routeConfig: {
-        component: route.routeConfig ? route.routeConfig.component : undefined,
-      },
+      routeConfig: route.routeConfig
```
Comment (brandonroberts) [inline modules/router-store/src/serializer.ts]: Shouldn't the `routeConfig` remain an empty object if its not defined to keep the existing behavior?

Comment (brandonroberts) [reply modules/router-store/src/serializer.ts]: Flag is as a breaking change. I'd rather the behavior be consistent and this would be the time to break it.

Comment (timdeschryver) [reply modules/router-store/src/serializer.ts]: Something like this? I have some troubles to properly word this.

Comment (brandonroberts) [reply modules/router-store/src/serializer.ts]: 👍
