### PR TITLE
fix(schematics): avoid lastIndexOf error while creating store schematics (#1659)

### LINKED ISSUE #1659: Schematics-Store: lastIndexOf
I try to check result and forgot write a store name:

```
$ ng g store -m modules/root-store -d
```

**Result:**
```
Cannot read property 'lastIndexOf' of undefined
```
image

there is no check if [options.path exist](https://github.com/ngrx/platform/blob/master/modules/schematics/src/store/index.ts#L136)

### PR DESCRIPTION
**Pull request by EnricoVogt**
fix(schematics): avoid lastIndexOf error while creating store schematics (#1659)

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #1659

## What is the new behavior?

Now its possible to create a store schematic without a name if its called with the "--root" flag, otherwise a name is necessary.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by King-i** [comment]
My 2 cents is if `name` is a required parameter then it may be better for it to be specified in `schema.json` under `required` which will prevent a user being able to run the schematic as stated in the schematics specifications, checking if the value was provided but having it declared as a required type in `schema.ts` defeats the purpose of the type system and the configuration via schema, if unit tests are required to confirm that `schema.json` matches `schema.ts` then that can be done via a AST read and compare?

**Comment by EnricoVogt** [comment]
I think the name parameter should not be required. If you create a rootstate (--root) the name is definitely not used. For my part i wont write something that is not neccesarry.

I have an open mind for other solutions.
I will wait for a advice how to solve it.

@brandonroberts 
@timdeschryver

**Comment by King-i** [comment]
If that's the case then no it shouldn't be set as required, however the definition says its required, so therefore the schema interface needs to be updated to have `name` set as optional, which may have caught this bug in the original unit tests in the first place.

File: modules/schematics/schematics-core/utility/parse-name.ts [hunk 1]
```diff
@@ -5,7 +5,7 @@ export interface Location {
   path: Path;
 }
 
-export function parseName(path: string, name: string): Location {
+export function parseName(path: string, name: string = ''): Location {
```
Comment (timdeschryver) [inline modules/schematics/schematics-core/utility/parse-name.ts]: I think we would want to scope this change specific to the store shematics.
To do this, we should default to an empty string at https://github.com/ngrx/platform/blob/3d0642867d6f4443a3fcfce194bc1112546ededd/modules/schematics/src/store/index.ts#L134

Comment (EnricoVogt) [reply modules/schematics/schematics-core/utility/parse-name.ts]: I will change this.

Comment (EnricoVogt) [reply modules/schematics/schematics-core/utility/parse-name.ts]: @timdeschryver i changed it now

File: modules/schematics/src/store/index.spec.ts [hunk 2]
```diff
@@ -215,4 +215,31 @@ describe('Store Schematic', () => {
...
+    expect(thrownError).toBeDefined();
+  });
+
+  it('should pass if a root state name is not specified', () => {
+    const options = {
+      ...defaultOptions,
+      name: undefined,
+    };
+
+    expect(function() {
```
Comment (timdeschryver) [inline modules/schematics/src/store/index.spec.ts]:
```suggestion
    expect(() => {
```

File: modules/schematics/src/store/index.spec.ts [hunk 3]
```diff
@@ -215,4 +215,31 @@ describe('Store Schematic', () => {
...
+      root: false,
+    };
+
+    let thrownError: Error | null = null;
+    try {
+      schematicRunner.runSchematic('store', options, appTree);
+    } catch (err) {
+      thrownError = err;
+    }
+    expect(thrownError).toBeDefined();
```
Comment (timdeschryver) [inline modules/schematics/src/store/index.spec.ts]:
```suggestion
    expect(() => {
      schematicRunner.runSchematic('store', options, appTree);
    }).toThrowError('Please provide a name for the feature state');
```

File: modules/schematics/src/store/index.spec.ts (hunk 2 above)
Comment (EnricoVogt) [reply modules/schematics/src/store/index.spec.ts]: Done.

File: modules/schematics/src/store/index.spec.ts (hunk 3 above)
Comment (EnricoVogt) [reply modules/schematics/src/store/index.spec.ts]: Did this for my Test now. There is another Test "should fail if specified module does not exist" which use also the `try catch` - should i change this also?

Comment (timdeschryver) [reply modules/schematics/src/store/index.spec.ts]: Not in the PR, you can open up a new PR if you would like to
