### PR TITLE
fix(store): allow primitive types

### LINKED ISSUE #2966: Inferred generic type of reducers Number/String/Boolean instead of number/string/boolean
When the state is a `number`, `string` or `boolean`, and the reducer function uses no parameters (`() => newState`), the generic type of the action reducer is wrongly inferred to be `Number`, `String` or `Boolean`.

This leads to Typescript errors either in `createReducer()` itself (depending on the order or the action reducers) or later on.

This was not an issue in `@ngrx/store` v10 - I hit this as I've upgraded to v11.

## Minimal reproduction of the bug/regression with instructions:

Reproduction in the [Typescript playground](https://www.typescriptlang.org/play?noUnusedLocals=true&noUnusedParameters=true&ts=4.2.3#code/JYWwDg9gTgLgBAbzgQQMY2BAdgGhezLAJQFMATAV1RKj1ShIEMYS0Ns6HmTTLra4HOGCgQwAZzgBfOADNRIOAHIAAlgDmUAB4B6cTGgklAbgBQp1Nn1xgWYBkYAbAMoxuALjhYKIAEY04AF44AAYzCyt4cRIYNkIguHomFjjsAAolaJglPBExcQAeJAA3JwoST28-AKkAPjSASgazSyxrBizUrASk7i6MjpilZvMSLUhYRMi5RmBHW3VeKgDg3pYl-jTTOBs7Bxc3FhxtwSw0zoIhNIB9fW48ErKSaQag2rhSx3KG4530wdil1wcEab129mATlc3B+phGpjGE3grWsAHdoABrBYbFaJLjrcjLKBbHa2CFQw4kX6nNIArp4UGBd5k-bQliwv5nC7sYE3O5HRAfJ4vMGfb7HeGI6DI6aIkjochdHFQTxKwn8ApVfwCLrvYLoqBYjTKsxSyYo+CMdAUJxqvg0VVA5UFAByPm1eF1CQNRsW6poxiAA).

```ts
import { Action, ActionReducer, createAction, createReducer, on, props } from '@ngrx/store';

const initialState: number = 0;

const setAction = createAction('set', props<{ value: number }>());
const resetAction = createAction('reset');

export const failingReducer = createReducer(
  initialState,
  on(setAction, (_state, { value }) => value),  // Typescript error
  on(resetAction, () => initialState),
);

export const workingReducer = createReducer(
  initialState,
  on(resetAction, () => initialState),
  on(setAction, (_state, { value }) => value),
);

export const expectedActionReducer: ActionReducer<number, Action> = workingReducer;  // Typescript error
export const actualActionReducer: ActionReducer<Number, Action> = workingReducer;
```

## Expected behavior:

If the state is `number`, `string`, or `boolean`, reducers' inferred generic type should be the same, even if there is a "reset-style" action reducer.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx: 11.0.1
Typescript: 4.1.5 / 4.2.3

## Other information:

The workaround is to add the state argument to the reducer function even though it is not needed:

```ts
export const reducer = createReducer(
  initialState,
  on(setAction, (_state, { value }) => value),
  on(resetAction, (_state) => initialState),
);

// works!
export const expectedActionReducer: ActionReducer<number, Action> = reducer;
```

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[X] No

### PR DESCRIPTION
**Pull request by timdeschryver**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #2966

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

File: modules/store/spec/types/utils.ts [hunk 1]
```diff
@@ -1,6 +1,6 @@
 export const compilerOptions = () => ({
   moduleResolution: 'node',
-  target: 'es2017',
+  target: 'es5',
```
Comment (timdeschryver) [inline modules/store/spec/types/utils.ts:3]: I had to change this to reproduce the issue.
To be honest, I'm not sure why because the snippet does also fail with `es2017` in the TS playground.

Comment (timdeschryver) [reply modules/store/spec/types/utils.ts]: I added an extra test for safety.

**Review by brandonroberts — APPROVED** [review]
