### PR TITLE
docs: fix typo on createFeature page

### LINKED ISSUE #3220: Fix typo in `createFeature` docs
There is one typo in `createFeature` docs:

create-feature-api

Underlined text "a the selector" should be replaced with "and a selector".

### PR DESCRIPTION
**Pull request by snutij**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #3220

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

File: modules/store/src/feature_creator.ts [hunk 1]
```diff
@@ -34,7 +34,7 @@ type NotAllowedFeatureStateCheck<
  *
  * @param featureConfig An object that contains a feature name and a feature reducer.
  * @returns An object that contains a feature name, a feature reducer,
- * a feature selector, a the selector for each feature state property.
+ * a feature selector and a selector for each feature state property.
```
Comment (timdeschryver) [inline modules/store/src/feature_creator.ts:37]: The comma should still be here.

```suggestion
 * a feature selector, and a selector for each feature state property.
```

**Review by markostanimirovic — APPROVED** [review]

File: modules/store/src/feature_creator.ts (hunk 1 above)
Comment (snutij) [reply modules/store/src/feature_creator.ts]: Sorry about that, I thought that in English too, we don't write a comma before the "and" word. I fixed this 👍

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks @snutij!
