### PR TITLE
chore: fix vitest setup in new docs

### LINKED ISSUE #4917: [New Docs]: splitVendorChunkPlugin is deprecated in vite.config.ts
### Which @ngrx/* package(s) are the source of the bug?

component-store

### Minimal reproduction of the bug/regression with instructions

NA

### Expected behavior

```ts
/// <reference types="vitest" />
import analog from '@analogjs/platform';
import { defineConfig } from 'vite';
import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';
import ngrxStackblitzPlugin from './src/tools/vite-ngrx-stackblits.plugin';

export default defineConfig(({ mode }) => ({
  root: __dirname,
  cacheDir: '../../node_modules/.vite',

  build: {
    outDir: '../../dist/projects/www/client',
    reportCompressedSize: true,
    target: ['es2020'],
    rollupOptions: {
      output: {
        manualChunks(id) {
          if (id.includes('node_modules')) {
            return 'vendor';
          }
        },
      },
    },
  },

  server: {
    fs: {
      allow: ['.'],
    },
    headers: {
      'Cross-Origin-Embedder-Policy': 'require-corp',
      'Cross-Origin-Opener-Policy': 'same-origin',
    },
  },

  plugins: [
    analog({
      static: true,
      content: {
        highlighter: 'shiki',
        shikiOptions: {
          highlighter: {
            additionalLangs: ['sh'],
          },
        },
      },
    }),
    nxViteTsPaths(),
    ngrxStackblitzPlugin(),
  ],

  test: {
    globals: true,
    environment: 'jsdom',
    setupFiles: ['src/test-setup.ts'],
    include: ['**/*.spec.ts'],
    reporters: ['default'],
  },

  define: {
    'import.meta.vitest': mode !== 'production',
  },
}));
```

Using manualChunks, causes a problem as `Not all code paths return a value.ts(7030)`.  I think a `Not Found` component is missing.  

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NA

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### LINKED ISSUE #4918: [New Docs]: Vitest setup has missing types and test-setup.ts uses deprecated methods
### Which @ngrx/* package(s) are the source of the bug?

component-store

### Minimal reproduction of the bug/regression with instructions

`tsconfig.editor.json` gives a  "Cannot find type definition file for 'vitest/globals'" warning.  

`test-setup.ts` has `BrowserDynamicTestingModule` and `platformBrowserDynamicTesting` deprecations.  

### Expected behavior

This seems to be mostly unused boilerplate.  I don't know if you want to remove this or fix it. 

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NA

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### LINKED ISSUE #4930: [New Docs]: Invalid SCSS syntax in component style blocks
### Which @ngrx/* package(s) are the source of the bug?

component-store

### Minimal reproduction of the bug/regression with instructions

Inline `styles` can't use SCSS syntax.  During testing (testing `npx nx run www:test` doesn't work yet on `main`), you get an error about the CSS not being correct and the full CSS code is printed in the terminal.

The [www home page component](https://github.com/ngrx/platform/blob/b94010480e5c71d81acfe352afe07d655dfb5c45/projects/www/src/app/pages/(home).page.ts#L59) has invalid syntax and its not the only component.

### Expected behavior

SCSS can be moved into its own file and imported with `styleUrls`.  Most of the most invalid syntax is confined to viewport rules so the incorrect declarations can be redone and separated.  Adding extra files may be break intended analog file structure.  Any preference for a fix here?

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NA

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by jdegand**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [X] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[X] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #4917 
Closes #4918
Closes #4930 

## What is the new behavior?

Tests will run from the `www` folder (`npx nx run www:test`).  There is a warning from `tsconfig.spec.json` file about missing types from `vitest`, but this doesn't prevent tests from running.  I've tried many different changes and this never goes away.  The npm packages got updated when I ran an analog command to regenerate the files.

## Does this PR introduce a breaking change?

```
[ ] Yes
[X] No
```

## Other information

### CODE REVIEW

**Comment by jdegand** [comment]
I just ran tests on `main` and the signals tests fail there as well.  So that failure doesn't appear related to these code changes.

**Comment by markostanimirovic** [comment]
`www` should be removed from `--exclude`:

- https://github.com/ngrx/platform/blob/main/.github/workflows/ci.yml#L64
- https://github.com/ngrx/platform/blob/main/.github/workflows/main.yml#L66

**Comment by jdegand** [comment]
@markostanimirovic The `www` tests fail because of #4930.  I still don't get why the signals tests fail in this PR, but not in other ones.  The signals tests timeout and maybe there is a potential memory leak.

**Comment by markostanimirovic** [comment]
> @markostanimirovic The `www` tests fail because of #4930. I still don't get why the signals tests fail in this PR, but not in other ones. The signals tests timeout and maybe there is a potential memory leak.

@jdegand Let's then fix #4930 first. I left a comment there.

**Comment by jdegand** [comment]
@markostanimirovic I added the `angular` plugin, but I didn't put it ahead of the `analog` plugin.  The `www` tests now pass.

**Comment by jdegand** [comment]
The `manualChunks` change could be source of signals tests failure.  Maybe, the parsing is too big and then those tests timeout.

**Comment by jdegand** [comment]
Excluded examples folder from tests in `www`.  Are these example projects going to be updated or a few removed?

The use of a constructor in place of an `ngOnInit` call may explain the injector error in `app.component.ts`.

**Comment by timdeschryver** [comment]
> Excluded examples folder from tests in `www`. Are these example projects going to be updated or a few removed?
> 
> The use of a constructor in place of an `ngOnInit` call may explain the injector error in `app.component.ts`.

The examples are referenced within our docs, or offered as a Stackblitz project.
We can go over them to see if the spec files are needed or can be removed.
For now I think it's good to exclude them from the tests.

**Comment by jdegand** [comment]
Need to further investigate issues with `angular-vitest-plugin`.   There are a few issues that are unresolved with Vitest's latest changes:

```
  resolve: {
    conditions: [...defaultClientConditions],
  },
```
 is a workaround.

I tried using a zoneless `vite.config.ts` in `www` from the analog docs.  It didn't seem to help.

I have started looking at more files for issues.  There definitely appears to be a misconfiguration somewhere.  

The signals tests always timeout.  The timeout failures are all related to `zone.js`.   An import issue in a `test-setup`?

Update: `cacheDir` scope could be important.  All tests pull from same cache so race conditions and flakiness.

**Comment by jdegand** [comment]
The signals folder `vite.config` likely needs to have `complierOptions` and `target` of `es2016` so the zone.js imports and tests work. 

```
/// <reference types="vitest" />

import angular from '@analogjs/vite-plugin-angular';

import { nxViteTsPaths } from '@nx/vite/plugins/nx-tsconfig-paths.plugin';

import { defineConfig } from 'vite';

// https://vitejs.dev/config/
export default defineConfig(({ mode }) => {
  return {
    root: __dirname,
    plugins: [
      angular(),
      nxViteTsPaths(),
    ],
    test: {
      globals: true,
      pool: 'forks',
      environment: 'jsdom',
      setupFiles: ['test-setup.ts'],
      include: ['**/*.spec.ts'],
      reporters: ['default']
    },
    define: {
      'import.meta.vitest': mode !== 'production',
    },
  };
});
```

**Comment by jdegand** [comment]
There was an error in the configuration for `www` and I used `inlineStyles` inside `angular` vs `analog`.  The newer version of the plugin doesn't require the `vite` object key.  

Changing `Object.assign` and using `globalThis` seemed to help the signals tests although there is still one test timing out.

**Comment by jdegand** [comment]
@timdeschryver The `www` tests still can fail (inconsistent). 

Below is an `app.component` change that makes the tests pass:

```ts
import {
  Component,
  Injector,
  PLATFORM_ID,
  inject,
  OnDestroy,
} from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { isPlatformBrowser } from '@angular/common';
import { MenuComponent } from './components/menu.component';
import { MarkdownSymbolLinkComponent } from './components/docs/markdown-symbol-link.component';
import { AlertComponent } from './components/docs/alert.component';
import { CodeExampleComponent } from './components/docs/code-example.component';
import { CodeTabsComponent } from './components/docs/code-tabs.component';
import { StackblitzComponent } from './components/docs/stackblitz.component';
import { FooterComponent } from './components/footer.component';

@Component({
  selector: 'ngrx-root',
  imports: [
    RouterOutlet,
    MenuComponent,
    MarkdownSymbolLinkComponent,
    AlertComponent,
    CodeExampleComponent,
    StackblitzComponent,
    FooterComponent,
  ],
  template: `
    <ngrx-menu></ngrx-menu>
    <router-outlet></router-outlet>
    <ngrx-footer></ngrx-footer>
  `,
  styles: [
    `
      :host {
        display: block;
        position: relative;
        width: calc(100% - 270px);
        left: 270px;
        @media only screen and (max-width: 1280px) {
          width: 100%;
          left: 0;
        }
      }

      ngrx-menu {
        position: fixed;
        top: 0;
        left: 0;
      }
    `,
  ],
})
export class AppComponent implements OnDestroy {
  private isAlive = true;
  private injector = inject(Injector);
  private platformId = inject(PLATFORM_ID);

  constructor() {
    if (isPlatformBrowser(this.platformId)) {
      this.installCustomElements();
    }
  }

  ngOnDestroy(): void {
    this.isAlive = false;
  }

  async installCustomElements() {
    if (!this.isAlive) return;

    const { createCustomElement } = await import('@angular/elements');

    if (!this.isAlive) return;

    const symbolLinkElement = createCustomElement(MarkdownSymbolLinkComponent, {
      injector: this.injector,
    });
    customElements.define('ngrx-docs-symbol-link', symbolLinkElement);

    if (!this.isAlive) return;

    const alertElement = createCustomElement(AlertComponent, {
      injector: this.injector,
    });
    customElements.define('ngrx-docs-alert', alertElement);

    if (!this.isAlive) return;

    const codeExampleElement = createCustomElement(CodeExampleComponent, {
      injector: this.injector,
    });
    customElements.define('ngrx-code-example', codeExampleElement);

    if (!this.isAlive) return;

    const codeTabsElement = createCustomElement(CodeTabsComponent, {
      injector: this.injector,
    });
    customElements.define('ngrx-code-tabs', codeTabsElement);

    if (!this.isAlive) return;

    const stackblitzElement = createCustomElement(StackblitzComponent, {
      injector: this.injector,
    });
    customElements.define('ngrx-docs-stackblitz', stackblitzElement);
  }
}
```

**Comment by jdegand** [comment]
@timdeschryver I updated the app component and changed the `test-setup`.  I ran the `www` tests many times and they never failed.  I think this should be it although the analog plugin API is tweaked in the next version so the vite config will need a change when that dependency is updated.

**Review by markostanimirovic — APPROVED** [review]

File: projects/www/src/app/app.component.ts [hunk 1]
```diff
@@ -47,39 +52,56 @@ import { FooterComponent } from './components/footer.component';
...
   }
 
+  ngOnDestroy(): void {
+    this.isAlive = false;
+  }
+
   async installCustomElements() {
+    if (!this.isAlive) return;
+
     const { createCustomElement } = await import('@angular/elements');
```
Comment (timdeschryver) [inline projects/www/src/app/app.component.ts]: I think the flaky tests are because of this import.
If we change this to be a file import (at the top of the file), then the error also goes away.

Comment (jdegand) [reply projects/www/src/app/app.component.ts]: It definitely could be a cause.  Analog uses `vmThreads` as default and this can have leakage across tests and problems with dynamic imports.

But I think the flakiness is mostly tied to the `injector` issue.  I went back to the original `app.component.ts` and added `pool:threads` and `pool:forks` to `vite.config.ts` and still got the unhandled error failure.

After I changed the spec file with this, the tests pass:

```ts
  beforeEach(async () => {
    await TestBed.configureTestingModule({
      providers: [provideRouter([])],
      imports: [AppComponent],
      teardown: { destroyAfterEach: false } // adding this seems to be enough
    }).compileComponents();
  });   
```

So the extra variable added and all the conditionals isn't truly necessary.  I'll wait to hear your thoughts before I change it again.

Comment (timdeschryver) [reply projects/www/src/app/app.component.ts]: I'm not a big fan of modifying production code for testing purposes.
Without the async block I wasn't able to reproduce the error, so I'm fine with making this method synchronous.
I also prefer to keep the destroy, just to make sure everything is cleaned up as expected.

Comment (jdegand) [reply projects/www/src/app/app.component.ts]: This combination also works: 

```ts
import { Component, Injector, PLATFORM_ID, inject } from '@angular/core';
import { RouterOutlet } from '@angular/router';
import { isPlatformBrowser } from '@angular/common';
import { MenuComponent } from './components/menu.component';
import { MarkdownSymbolLinkComponent } from './components/docs/markdown-symbol-link.component';
import { AlertComponent } from './components/docs/alert.component';
import { CodeExampleComponent } from './components/docs/code-example.component';
import { CodeTabsComponent } from './components/docs/code-tabs.component';
import { StackblitzComponent } from './components/docs/stackblitz.component';
import { FooterComponent } from './components/footer.component';

@Component({
  selector: 'ngrx-root',
  imports: [
    RouterOutlet,
    MenuComponent,
    MarkdownSymbolLinkComponent,
    AlertComponent,
    CodeExampleComponent,
    StackblitzComponent,
    FooterComponent,
  ],
  template: `
    <ngrx-menu></ngrx-menu>
    <router-outlet></router-outlet>
    <ngrx-footer></ngrx-footer>
  `,
  styles: [
    `
      :host {
        display: block;
        position: relative;
        width: calc(100% - 270px);
        left: 270px;
        @media only screen and (max-width: 1280px) {
          width: 100%;
          left: 0;
        }
      }

      ngrx-menu {
        position: fixed;
        top: 0;
        left: 0;
      }
    `,
  ],
})
export class AppComponent {
  injector = inject(Injector);
  platformId = inject(PLATFORM_ID);

  constructor() {
    if (isPlatformBrowser(this.platformId)) {
      this.installCustomElements();
    }
  }

  async installCustomElements() {
    const { createCustomElement } = await import('@angular/elements');

    const symbolLinkElement = createCustomElement(MarkdownSymbolLinkComponent, {
      injector: this.injector,
    });
    customElements.define('ngrx-docs-symbol-link', symbolLinkElement);

    const alertElement = createCustomElement(AlertComponent, {
      injector: this.injector,
    });
    customElements.define('ngrx-docs-alert', alertElement);

    const codeExampleElement = createCustomElement(CodeExampleComponent, {
      injector: this.injector,
    });
    customElements.define('ngrx-code-example', codeExampleElement);

    const codeTabsElement = createCustomElement(CodeTabsComponent, {
      injector: this.injector,
    });
    customElements.define('ngrx-code-tabs', codeTabsElement);

    const stackblitzElement = createCustomElement(StackblitzComponent, {
      injector: this.injector,
    });
    customElements.define('ngrx-docs-stackblitz', stackblitzElement);
  }
}
```

```ts
import { TestBed } from '@angular/core/testing';
import { AppComponent } from './app.component';
import { describe, beforeEach, it, expect } from 'vitest';
import { provideRouter } from '@angular/router';
import { PLATFORM_ID } from '@angular/core';

describe('AppComponent', () => {
  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [
        provideRouter([]),
        { provide: PLATFORM_ID, useValue: 'server' },
      ],
      imports: [AppComponent],
    });
  });

  it('should create the app', () => {
    const fixture = TestBed.createComponent(AppComponent);
    const app = fixture.componentInstance;
    expect(app).toBeTruthy();
  });
});
```

Comment (timdeschryver) [reply projects/www/src/app/app.component.ts]: That's fine as well
