### PR TITLE
fix(signals): allow using signalStore and signalState in TS libs

### LINKED ISSUE #4151: ngrx/signals type error "Exported variable 'CounterStore' has or is using name 'STATE_SIGNAL' from external module "node_modules/@ngrx/signals/src/signal-state" but cannot be named"
### Which @ngrx/* package(s) are the source of the bug?

signals

### Minimal reproduction of the bug/regression with instructions

Copy the code from the ngrx/signals anouncement:
[Announcing NgRx v17: Introducing NgRx Signals](https://dev.to/ngrx/announcing-ngrx-v17-introducing-ngrx-signals-operators-performance-improvements-workshops-and-more-55e4)

```typescript
import { signalStore, withState } from '@ngrx/signals';

export const CounterStore = signalStore(withState({ count: 0 }));
```

image

### Expected behavior

I am working in an Nx mono repo. If I add the store ts file directly in the app (`apps` folder), the error is not present. The error only happens when the file is created in an nx library (`libs` folder).

This works correctly.
image

This does not work.
image

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

ngrx/signals: v17.0.0
Angular: v17.0.1
Nx: v17.1.2
Node: v18.17.1

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by markostanimirovic**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #4151 

## What is the new behavior?

`signalStore` and `signalState` can be used/exported in projects that have `tsconfig` with `"declaration": true`.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

This is a workaround for the following TS bug: https://github.com/microsoft/TypeScript/issues/37888

### CODE REVIEW

File: modules/signals/src/signal-store-models.ts [hunk 1]
```diff
@@ -15,12 +15,11 @@ export type SignalStoreSlices<State> = IsKnownRecord<
...
   : {};
 
-export type SignalStore<FeatureResult extends SignalStoreFeatureResult> =
+export type SignalStoreProps<FeatureResult extends SignalStoreFeatureResult> =
   Prettify<
     SignalStoreSlices<FeatureResult['state']> &
       FeatureResult['signals'] &
-      FeatureResult['methods'] &
-      SignalStateMeta<Prettify<FeatureResult['state']>>
+      FeatureResult['methods']
```
Comment (markostanimirovic) [inline modules/signals/src/signal-store-models.ts:22]: A workaround for this TS bug is to always put a unique symbol inside of the named type.

**Before:**

The `STATE_SIGNAL` was appended to the dynamic `SignalStore` type by prettifying the intersection.

```ts
const CounterStore = signalStore(withState({ count: 0 }));
// type: Type<{ count: Signal<number>; [STATE_SIGNAL]: WritableSignal<{ count: number }> }>
```

**After:**

The `STATE_SIGNAL` is always exported as a part of the `StateSignal` type.

```ts
const CounterStore = signalStore(withState({ count: 0 }));
// type: Type<{ count: Signal<number>; } & StateSignal<{ count: number }>>
```

File: modules/signals/src/deep-signal.ts [hunk 2]
```diff
@@ -8,7 +8,7 @@ import { IsKnownRecord } from './ts-helpers';
 
 // An extended Signal type that enables the correct typing
 // of nested signals with the `name` or `length` key.
-interface Signal<T> extends NgSignal<T> {
+export interface Signal<T> extends NgSignal<T> {
```
Comment (markostanimirovic) [inline modules/signals/src/deep-signal.ts:11]: This export fixes the same compilation error in TS libraries with `declaration: true` when `signalState` is used. The problem was caused by another unique symbol - Angular's `SIGNAL`.

Comment (alex-okrushko) [reply modules/signals/src/deep-signal.ts:11]: 👍

File: modules/signals/src/signal-store-models.ts (hunk 1 above)
Comment (alex-okrushko) [reply modules/signals/src/signal-store-models.ts:22]: Makes sense. 

`StateSignal` has to be added to the public APIs `index.ts` as well, right?

Comment (markostanimirovic) [reply modules/signals/src/signal-store-models.ts:22]: It's not needed. We can keep it private.

**Review by alex-okrushko — APPROVED** [review]

**Comment by otkrivashkin** [comment]
Please, somebody approve it)

**Review by brandonroberts — APPROVED** [review]
