### PR TITLE
fix(www): Make Guide Pages Responsive #4817

### LINKED ISSUE #4817: [New Docs] Make Guide Pages Responsive
### Information

Make guide pages responsive:

guide-page

For inspiration, take a look at existing NgRx docs and new Angular docs.

### Documentation page

/guide/{content-file-name}

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by DuskoPeric**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Guide pages are not responsive

Closes #4817

## What is the new behavior?
Guide pages are responsive

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

**Comment by DuskoPeric** [comment]
Hi @timdeschryver 
I think the ToC is broken on large screens as well. Maybe we can create a new issue to fix the ToC functionality.

**Comment by timdeschryver** [comment]
@DuskoPeric 😲 you're right!
I will create a new issue to take a look into this behavior.
Removing the ToC for mobile can be done in this PR, or would you rather keep the ToC?

**Comment by DuskoPeric** [comment]
Hi @timdeschryver , based on Marko's suggestion, I created a dropdown for the ToC on mobile screens.

**Comment by timdeschryver** [comment]
@DuskoPeric that's a great idea, thanks!
I will go over it tomorrow.

**Review by timdeschryver — APPROVED** [review]

File: projects/www/src/app/components/docs/markdown-article.component.ts [hunk 1]
```diff
@@ -126,6 +193,7 @@ export class MarkdownArticleComponent implements OnDestroy {
   articleRef: Signal<ElementRef<HTMLElement>> = viewChild.required('article');
   headings = signal<Heading[]>([]);
   activeHeadingId = signal<string | null>(null);
+  isMenuOpen = signal<boolean>(false);
```
Comment (markostanimirovic) [inline projects/www/src/app/components/docs/markdown-article.component.ts]:
```suggestion
  isMenuOpen = signal(false);
```

**Review by markostanimirovic — APPROVED** [review]
