### PR TITLE
fix(www): Add padding to code snippets

### LINKED ISSUE #4811: [New Docs] Add padding to code snippets
### Information

The code snippets can use a little padding.
It currently sticks to the borders.

Image

### PR DESCRIPTION
**Pull request by DuskoPeric**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/main/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Code snippetets sticks to the borders

Closes #4811

## What is the new behavior?
Code snippets have padding

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

File: projects/www/src/app/components/docs/code-example.component.ts [hunk 1]
```diff
@@ -27,8 +27,9 @@ import { Component, Input } from '@angular/core';
       }
 
       .body {
-        padding: 0 0px;
+        padding: 16px 20px;
         overflow-x: wrap;
+        background-color: rgb(36, 41, 46);
```
Comment (timdeschryver) [inline projects/www/src/app/components/docs/code-example.component.ts]: Thanks!
I think we can apply this to `pre` tags, to also cover the code samples that don't use this component.
E.g. for the installation commands at https://deploy-preview-4812--ngrx-site-v19.netlify.app/guide/entity/install

This also removes the need to add the background color here.

**Review by timdeschryver — APPROVED** [review]
Thanks @DuskoPeric !

**Review by markostanimirovic — APPROVED** [review]
