### PR TITLE
No logs about empty state for tests with mocked store

### LINKED ISSUE #2363: MockStore selectors resulting in warning logs
## Minimal reproduction of the bug/regression with instructions:

Currently all the tests that use a mockstore with mocked selectors, [will log the warning that the state does not exists](https://github.com/ngrx/platform/blob/master/modules/store/src/selector.ts#L618).

This is normal because when we define a mocks store, we don't define the state object.

## Expected behavior:

It should not be logged while running tests.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Angular 9
NgRx 9-beta.1

## Other information:

AFAIK, it isn't possible to detect when we run in a test environment.
But we could set a property on the state (`__ngrxMockEnvironment__`), and the `createFeatureSelector` could use this property to check if it the warning has to logged or not.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by evgenyfedorenko**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

This code adds an internal setting and a setter for mock store environment.
When set it suppresses the logs about the state which does not exist.

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Console warn logs numerous logs for mocked store which should not happen

Closes #2363

## What is the new behavior?

Logs will be suppressed

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information
This is a copy of https://github.com/ngrx/platform/pull/2420

### CODE REVIEW

File: modules/store/testing/src/testing.ts [hunk 1]
```diff
@@ -20,6 +21,7 @@ export interface MockStoreConfig<T> {
 export function provideMockStore<T = any>(
   config: MockStoreConfig<T> = {}
 ): Provider[] {
+  setNgrxMockEnvironment(true);
```
Comment (timdeschryver) [inline modules/store/testing/src/testing.ts:24]: Can there also be a test to verify that `setNgrxMockEnvironment` is called here?
