### PR TITLE
fix(effects): dispatch init action once

### LINKED ISSUE #2106: Lazy loaded effect initialized multiple times if used in multiple routes
## Expected behavior:

I have a lazy loaded module that imports EffectsModule.forFeature(...) and is accessible from multiple routes within the application.  In other words loadChildren is defined for this module multiple times in the app-routing.module.ts file:

/a/b/feature
/c/d/feature

When configured like this ngrxOnInitEffects is triggered multiple times when visiting each route. I would have expected it to only execute one time.

If this is intended what is the suggested approach to ensuring that init code would only run one time?

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

angular @ 8.1.1
ngrx @ 8.1.0

### PR DESCRIPTION
**Pull request by timdeschryver**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #2106

## What is the new behavior?

See the breaking change section below

## Does this PR introduce a breaking change?

```
[x] Yes
[ ] No
```

BREAKING CHANGE

Before
When the effect class was registered, the init action would be dispatched.
If the effect was provided in multiple lazy loaded modules, the init action would be dispatched for every module.

After
The init action is only dispatched once
The init action is now dispatched based on the identifier of the effect (via ngrxOnIdentifyEffects)

### CODE REVIEW

File: modules/effects/src/effect_sources.ts [hunk 1]
```diff
@@ -47,7 +41,21 @@ export class EffectSources extends Subject<any> {
...
     return this.pipe(
       groupBy(getSourceForInstance),
-      mergeMap(source$ => source$.pipe(groupBy(effectsInstance))),
+      mergeMap(source$ => {
+        return source$.pipe(
+          groupBy(effectsInstance),
+          tap(() => {
+            if (
+              onInitEffects in source$.key &&
+              typeof source$.key[onInitEffects] === 'function'
```
Comment (alex-okrushko) [inline modules/effects/src/effect_sources.ts]: I think we should push this logic back into lifecycle_hooks.ts and expose it has `isOnInitEffects(key): key is OnInitEffects` type guard

File: modules/effects/src/effect_sources.ts [hunk 2]
```diff
@@ -47,7 +41,21 @@ export class EffectSources extends Subject<any> {
...
+            ) {
+              this.store.dispatch(
+                source$.key[onInitEffects].bind(source$.key)()
```
Comment (alex-okrushko) [inline modules/effects/src/effect_sources.ts]: this would be the same as `((key: OnInitEffects) => key.ngrxOnInitEffects())(source$.key)`, right?

Do we need that much complexity here? maybe just `this.store.dispatch(source$.key.ngrxOnInitEffects())`? (after we get it through type-guard)

File: modules/effects/spec/effect_sources.spec.ts [hunk 3]
```diff
@@ -51,15 +56,52 @@ describe('EffectSources', () => {
...
+        return { type: '[EffectWithInitAction] Init' };
+      }
+    }
+    const store = TestBed.get(Store);
+
+    effectSources.addEffects(new EffectWithInitAction());
+    effectSources.addEffects(new EffectWithInitAction());
+
+    expect(store.dispatch).toHaveBeenCalledTimes(1);
+  });
```
Comment (alex-okrushko) [inline modules/effects/spec/effect_sources.spec.ts]: Can we please add a similar test but where effects class actually has 2 effects? (and should be called once)

File: modules/effects/src/effect_sources.ts (hunk 1 above)
Comment (timdeschryver) [reply modules/effects/src/effect_sources.ts]: I'll do this in another PR if that's OK.
Currently, all checks on lifecycle hooks are done in a similar way, in the next PR we can refactor all of them to type guards.

File: modules/effects/src/effect_sources.ts (hunk 2 above)
Comment (timdeschryver) [reply modules/effects/src/effect_sources.ts]: Great catch, I did it to bind `this` to the effect instance inside the `isOnInitEffects` function of the effect.

But this won't be possible AFAIK because we're using `Object.getPrototypeOf` to group the effect instances.

File: modules/effects/spec/effect_sources.spec.ts (hunk 3 above)
Comment (timdeschryver) [reply modules/effects/spec/effect_sources.spec.ts]: I addressed the feedback - thanks!
