### PR TITLE
fix(store): allow union of types in props

### LINKED ISSUE #2300: store: ActionCreator unable to take the union of types in props
## Minimal reproduction of the bug/regression with instructions:

```ts
      interface A {
        sameProp: 'A';
      }
      interface B {
        sameProp: 'B';
        extraProp: string;
      }
      type U = A | B;
      const foo = createAction('FOO', props<U>()); // <--- Error
``` 

Within conditional type of `PropsReturnType` the union type was unwrapped as `{_as: 'prop', _p: A} | {_as: 'prop', _p: B}` that creates issues further in `createAction` implementation.

## Expected behavior:
Unions should be allowed

## I would be willing to submit a PR to fix this issue

[x] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by alex-okrushko**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

Instead of modifying the type of the `Creator`, it appears to be better to add intersection `& NotAllowedCheck` where it used.

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

```typescript
     interface A {
        sameProp: 'A';
      }
      interface B {
        sameProp: 'B';
        extraProp: string;
      }
      type U = A | B;
      const foo = createAction('FOO', props<U>()); // <--- Error
```

Closes #2300 

## What is the new behavior?

Allows to take `props<U>()` where `U = A | B`.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

File: modules/store/src/models.ts [hunk 1]
```diff
@@ -75,17 +75,11 @@ export type FunctionIsNotAllowed<
...
   R extends object = object
-> = R extends any[]
-  ? ArraysAreNotAllowed
-  : R extends { type: any }
-    ? TypePropertyIsNotAllowed
-    : FunctionWithParametersType<P, R>;
+> = FunctionWithParametersType<P, R>;
 
-export type PropsReturnType<T extends object> = T extends any[]
+export type NotAllowedCheck<T extends object> = T extends any[]
```
Comment (timdeschryver) [inline modules/store/src/models.ts]: What is the difference between this type and `DisallowArraysAndTypeProperty` ? 
I believe `DisallowArraysAndTypeProperty` isn't used with this refactor, so we can also remove that type or mark it to be deleted in v9

File: modules/store/src/action_creator.ts [hunk 2]
```diff
@@ -121,10 +120,8 @@ export function createAction<T extends string, C extends Creator>(
   }
 }
 
-export function props<P extends object>(): PropsReturnType<P> {
-  // the return type does not match TypePropertyIsNotAllowed, so double casting
-  // is used.
-  return ({ _as: 'props', _p: undefined! } as unknown) as PropsReturnType<P>;
+export function props<P extends object>(): { _as: 'props'; _p: P } {
```
Comment (timdeschryver) [inline modules/store/src/action_creator.ts]: What about creating a `PropsConfig` type for `{ _as: 'props'; _p: P }`?

Comment (alex-okrushko) [reply modules/store/src/action_creator.ts]: Yes, we can do that.

File: modules/store/src/models.ts (hunk 1 above)
Comment (alex-okrushko) [reply modules/store/src/models.ts]: Did realize that we got `DisallowArraysAndTypeProperty` still hanging around. I removed it in favor of `NotAllowedCheck`, as it wasn't exported to the public api.

**Comment by alex-okrushko** [comment]
> Out of curiosity, what's the use case to provide a union type? 

The author of the code is being creative 😎
E.g. a limited list of strings are allowed, e.g. 'A', 'B', 'C' and 'D', which serve as a particular differentiator for the object, lets call it `type SomeKind`
When one of the kinds would require additional info, such as `extraRequiredProp` 🙂

See here: https://www.typescriptlang.org/play/index.html#code/C4TwDgpgBAyg9gWwgaQJYDsAmUC8UDkAgvlAD4EBCJ5+AwtQQCL4DcAUGxsBAE4BmAQwDG0AGJw4UAN5Q2UeVADWGTAC4oAUQAewHsOAAeeEjRYANAWIA+dgqgQdegEoQAjgFdUPCJgAKPODB1AGddDABzdgBfDi5eQREoCgEeaVk7ZSx1bSEAG3dMCCNEFBULInwbNhi2UEgoAFV0VDh0XChxSXJknnY2IVbQqAAjdSaWtrwpOQVMtUp8CwB6JagACwFgqAFc3KhgNehA4AmtjFgS00xqjgH0IYEx5tb26YyVdQqzGfkHXQEXB4vD5-IFPgh3ENhtBghBgIsbmwgA
