### PR TITLE
fix(component): fixes recursive rendering

### LINKED ISSUE #3246: *ngrxLet causes ASSERTION ERROR: Reached the max number of directives [Expected=> 1 != 1 <=Actual]
The issue seems to be when the observable emits while angular is still constructing the template.

## Minimal reproduction of the bug/regression with instructions:

Here's an example to reproduce

https://github.com/e-davidson/angular-issue-reproduction-2021

## Expected behavior:

The component should render with no errors.

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

NgRx 13, Angular 13, Node 14.17, OS wsl, browser chrome

## Other information:

I also submitted an issue to the angular team
https://github.com/angular/angular/issues/44231

If they do fix the issue this would still be a problem since createEmbeddedView will have been called an extra time when it shouldn't due to the recurssion.

I believe it can be easily fixed by not relying on the embeddedView to be null and instead have a field if it's the first time or not.

See here
https://github.com/ngrx/platform/blob/master/modules/component/src/let/let.directive.ts#L121

## I would be willing to submit a PR to fix this issue
Sure, I'd love to help if the team feels this is correct.

[x ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by e-davidson**
Handles edge case where rendering causes the observable to emit which causes
`ASSERTION ERROR: Reached the max number of directives [Expected=> 1 != 1 <=Actual]`

Change the logic to set `embeddedViewCreated` before calling `createEmbeddedView`, so if `ensureEmbeddedViewCreated` is called recursively it won't call `createEmbeddedView` a 2nd time. Also, we're calling `ensureEmbeddedViewCreated` after we setup the view context because if it gets called recursively the previous call stack will override the later value.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Closes #3246 

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

File: modules/component/src/let/let.directive.ts [hunk 1]
```diff
@@ -94,7 +94,7 @@ export class LetDirective<U> implements OnDestroy {
   // eslint-disable-next-line @typescript-eslint/naming-convention
   static ngTemplateGuard_ngrxLet: 'binding';
 
-  private embeddedView: any;
+  private embeddedviewCreated = false;
```
Comment (markostanimirovic) [inline modules/component/src/let/let.directive.ts:97]:
```suggestion
  private embeddedViewCreated = false;
```

or

```suggestion
  private isEmbeddedViewCreated = false;
```

File: modules/component/src/let/let.directive.ts [hunk 2]
```diff
@@ -168,11 +159,14 @@ export class LetDirective<U> implements OnDestroy {
     this.subscription = this.cdAware.subscribe({});
   }
 
-  createEmbeddedView() {
-    this.embeddedView = this.viewContainerRef.createEmbeddedView(
-      this.templateRef,
-      this.viewContext
-    );
+  ensureEmbeddedViewCreated() {
```
Comment (markostanimirovic) [inline modules/component/src/let/let.directive.ts:162]:
```suggestion
  private ensureEmbeddedViewCreated(): void {
```

**Review by markostanimirovic — CHANGES_REQUESTED** [review]

File: modules/component/src/let/let.directive.ts [hunk 3]
```diff
@@ -168,11 +159,14 @@ export class LetDirective<U> implements OnDestroy {
...
+    if (!this.embeddedviewCreated) {
+      this.embeddedviewCreated = true;
+      this.viewContainerRef.createEmbeddedView(
+        this.templateRef,
+        this.viewContext
+      );
+    }
```
Comment (markostanimirovic) [inline modules/component/src/let/let.directive.ts:169]: Removing public `createEmbeddedView` method is a breaking change (if someone uses `LetDirective` outside of the template 👀). Let's keep it for now and remove `ensureEmbeddedViewCreated`:

```ts
  createEmbeddedView() {
    this.isEmbeddedViewCreated = true;
    this.viewContainerRef.createEmbeddedView(
      this.templateRef,
      this.viewContext
    );
  }
```

File: modules/component/src/let/let.directive.ts [hunk 4]
```diff
@@ -117,26 +117,17 @@ export class LetDirective<U> implements OnDestroy {
   };
   private readonly updateViewContextObserver: Observer<U | null | undefined> = {
     next: (value: U | null | undefined) => {
-      // to have init lazy
-      if (!this.embeddedView) {
-        this.createEmbeddedView();
-      }
       this.viewContext.$implicit = value;
       this.viewContext.ngrxLet = value;
+      this.ensureEmbeddedViewCreated();
```
Comment (markostanimirovic) [inline modules/component/src/let/let.directive.ts:122]: Is there any reason why the `createEmbeddedView` is moved to the end of the callback?

**Review by markostanimirovic — CHANGES_REQUESTED** [review]

File: modules/component/src/let/let.directive.ts (hunk 4 above)
Comment (e-davidson) [reply modules/component/src/let/let.directive.ts:122]: Yes, if the recursion happens you want to make sure you're setting the latest value last.

I'm trying to avoid the following problem.

`next(0)` called 
Call `this.createEmbeddedView()` 
Set `isEmbeddedviewCreated = true`
Call `viewContainerRef.createEmbeddedView()`
`next(1)` called
Call `this.createEmbeddedView()` 
return to `next(1)`
Set `this.viewContext.ngrxLet = value` (value = 1)
return to `viewContainerRef.createEmbeddedView`
return to `this.createEmbeddedView` 
return to `next(0)`
Set `this.viewContext.ngrxLet = value` (value = 0) OOPS!

File: modules/component/src/let/let.directive.ts (hunk 1 above)
Comment (e-davidson) [reply modules/component/src/let/let.directive.ts]: Thanks, done.

File: modules/component/src/let/let.directive.ts (hunk 3 above)
Comment (e-davidson) [reply modules/component/src/let/let.directive.ts]: Good catch, I put the logic back to the way it was before except for changing order of setting the view context before rendering. Otherwise, the test I added would fail.

On a side point, outside the scope of this PR.
Would it make sense to deprecate and remove the function from the public API in the future?
If you call the function from your component the end result would be the content will get rendered twice. It's very hard to believe that would be desirable behavior.
The one use case that I can see where calling it yourself may be helpful is if you want your template to render even though the observable hadn't yet emitted. To support that scenario we can still stop you from rendering a second time by moving the `if(isEmbeddedviewCreated)`  logic to `createEmbeddedView`. Alternatively we can offer a config option to support this scenario.
We can create a new feature request if that makes sense.

Comment (markostanimirovic) [reply modules/component/src/let/let.directive.ts]: Yes, I agree that the `createEmbeddedView` method should not be public. Extending the `LetDirective` is not recommended approach at all. However, someone can do that, and we have to ensure that there are no breaking changes in minor/patch version updates.

**Review by markostanimirovic — APPROVED** [review]
LGTM 👍 Thanks @e-davidson!

**Comment by timdeschryver** [comment]
I'm going to trigger the CI by closing and reopening this PR..

**Review by timdeschryver — APPROVED** [review]

**Comment by timdeschryver** [comment]
Thanks @e-davidson
