### PR TITLE
fix(store): add Signal equal function for immutable object comparison

### LINKED ISSUE #3882: selectSignal() fires on every global state change
### Which @ngrx/* package(s) are the source of the bug?

store

### Minimal reproduction of the bug/regression with instructions

All selectors created with `selectSignal()` fire on every global state change, even if the related state received no update.

```
store = inject(Store);

constructor() {
   const myState = this.store.selectSignal(mySelector);
   effect(() => console.log(myState());
   setTimeout(() => {
      this.store.dispatch(
         changeOtherStateAction({ info: 'globale state changed' })
      );
   },  5_000);
}
```

**Why does this happen?**

The Angular team decided to emit a new Signal value for each object set, even if the reference stays the same.
This is an issue for working with immuable data (the default for NgRx state management).

The behavior can be fixes manually by configuring an equal function:

```
this.store.selectSignal(
   mySelector,
   { equal: (a, b) => a === b }
);
```

**Necessary change**

This equal compare behavior should be set automatically for `selectSignal()` as the current behavior is not expected by the developer that works with an immutable state pattern.

### Versions of NgRx, Angular, Node, affected browser(s) and operating system(s)

NgRx: 16 RC.0
Angular 16.0.0

### Other information

May affect `@ngrx/component-store` as well.

Credits to @manfredsteyer who found this issue.

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by mikezks**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: https://github.com/ngrx/platform/blob/master/CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Documentation has been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

All selectors created with `store.selectSignal()` fire on every global state change, even if the related state received no update.

Closes #3882 

## What is the new behavior?

If `selector(this.state())` returns the same object reference the computed Signal does not trigger a value update anymore.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

### CODE REVIEW

File: modules/store/src/store.ts [hunk 1]
```diff
@@ -112,7 +112,9 @@ export class Store<T = object>
     selector: (state: T) => K,
     options?: SelectSignalOptions<K>
   ): Signal<K> {
-    return computed(() => selector(this.state()), { equal: options?.equal });
+    return computed(() => selector(this.state()), {
+      equal: options?.equal || ((previous, current) => previous === current),
+    });
```
Comment (markostanimirovic) [inline modules/store/src/store.ts:117]: LGTM 👍 

Can you add a test to the `integration_signals.spec.ts` to verify this fix?

File: modules/store/spec/integration_signals.spec.ts [hunk 2]
```diff
@@ -130,4 +131,30 @@ describe('NgRx and Signals Integration spec', () => {
...
+      const todos = TestBed.runInInjectionContext(() =>
+        store.selectSignal((state) => state.todos)
+      );
+
+      const todosTriggerState = TestBed.runInInjectionContext(() =>
+        computed(() => {
+          todos();
+          return ++todosTriggerCount;
+        })
+      );
```
Comment (markostanimirovic) [inline modules/store/spec/integration_signals.spec.ts:148]: we should be able to use `selectSignal` and `computed` out of injection context:

```suggestion
      const todos = store.selectSignal((state) => state.todos);

      const todosTriggerState = computed(() => {
        todos();
        return ++todosTriggerCount;
      });
```

**Review by markostanimirovic — APPROVED** [review]

**Comment by mikezks** [comment]
If fix is OK:

- [ ] Review `@ngrx/component-store` `selectSignal()` as well.

**Review by brandonroberts — APPROVED** [review]

**Comment by brandonroberts** [comment]
Thanks @mikezks!
