### PR TITLE
Effects: Add support for effects of different instances of same class

### LINKED ISSUE #1246: Effects: Instantiating Effects multiple times, only first instance is run
## Minimal reproduction of the bug/regression with instructions:

When instantiating an effect multiple times and adding it to EffectSources, only the first instance is run, all others are ignored.

https://stackblitz.com/edit/angular-cfqrvf

## Expected behavior:

Adding instances through EffectSources.addEffects should work when providing multiple instances of the same class, so this should work:

```
class ConfigurableEffect {
  @Effect({ dispatch: false })
  doSth$ = timer(1000).pipe(
    tap(() => console.log(this.message))
  );

  constructor(private message: string) { }
}

@NgModule({
  imports: [BrowserModule, FormsModule, StoreModule.forRoot(() => true), EffectsModule.forRoot([])],
  declarations: [AppComponent, HelloComponent],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(effectSources: EffectSources) {
    effectSources.addEffects(new ConfigurableEffect("configA"));
    effectSources.addEffects(new ConfigurableEffect("configB"));
    // -> should run both "configA" and "configB" after 1 second, but only "configA" is run
  }
}
```

## Versions of NgRx, Angular, Node, affected browser(s) and operating system(s):

Latest

## Other information:

This is essentially blocking us from using effects in a configurable way.

## I would be willing to submit a PR to fix this issue

[ ] Yes (Assistance is provided if you need help submitting a pull request)
[ ] No

### PR DESCRIPTION
**Pull request by dummdidumm**
Fixes #1246 

With this change, it is possible to add different instances of the same class to the effects and have them running:

```
class ConfigurableEffect {
  @Effect({ dispatch: false })
  doSth$ = timer(1000).pipe(
    tap(() => console.log(this.message))
  );

  constructor(private message: string) { }
}

@NgModule({
  imports: [BrowserModule, FormsModule, StoreModule.forRoot(() => true), EffectsModule.forRoot([])],
  declarations: [AppComponent, HelloComponent],
  bootstrap: [AppComponent]
})
export class AppModule {
  constructor(effectSources: EffectSources) {
    effectSources.addEffects(new ConfigurableEffect("configA"));
    effectSources.addEffects(new ConfigurableEffect("configB"));
    // -> this did not work before, second effects instance was never run
  }
}
```

`EffectSources` still filters out effects which are already running, so no danger of running the same effects instance multiple times.

### CODE REVIEW

File: modules/effects/src/effect_sources.ts [hunk 1]
```diff
@@ -29,22 +21,42 @@ export class EffectSources extends Subject<any> {
    */
   toActions(): Observable<Action> {
     return this.pipe(
-      groupBy(getSourceForInstance),
-      mergeMap(source$ =>
-        source$.pipe(
-          exhaustMap(resolveEffectSource),
-          map(output => {
-            verifyOutput(output, this.errorHandler);
+      scan(
```
Comment (timdeschryver) [inline modules/effects/src/effect_sources.ts]: I might be overlooking something but won't the following accomplish the same thing?

```ts
groupBy(source => source),
```

Comment (dummdidumm) [reply modules/effects/src/effect_sources.ts]: You are completely right, thanks for noticing! I will update the PR.
